### ISSUE TITLE
ProjectParseException: java.io.IOException: Cannot run program "mvn" (in directory "/Users/lee5hx/Works/java_projects/gaias/gaia"): error=2, No such file or directory

### ISSUE THREAD

**Issue by lee5hx** [mopemope/meghanada-server#10]
## My Environment
- OS X 10.11.6
- emacs 25.1
- JDK 1.8
- meghanada-server 0.7.0

## 1.  *meghanada-server-log*   --debug
[2017-03-21 15:42:34,059][DEBUG][Main          :  73] main                   - set verbose flag(DEBUG)
[2017-03-21 15:42:34,061][DEBUG][Main          : 111] main                   - set port:55555, projectRoot:./, output:sexp
[2017-03-21 15:42:34,061][INFO ][Main          : 114] main                   - Meghanada-Server Version:0.7.0-0c49b50
[2017-03-21 15:42:34,070][DEBUG][Session       :  80] findProject            - finding project from '/Users/lee5hx/Works/java_projects/gaias/gaia/src/main/java/com/mindasset/gaia' ...
[2017-03-21 15:42:34,070][DEBUG][Session       :  80] findProject            - finding project from '/Users/lee5hx/Works/java_projects/gaias/gaia/src/main/java/com/mindasset' ...
[2017-03-21 15:42:34,071][DEBUG][Session       :  80] findProject            - finding project from '/Users/lee5hx/Works/java_projects/gaias/gaia/src/main/java/com' ...
[2017-03-21 15:42:34,071][DEBUG][Session       :  80] findProject            - finding project from '/Users/lee5hx/Works/java_projects/gaias/gaia/src/main/java' ...
[2017-03-21 15:42:34,071][DEBUG][Session       :  80] findProject            - finding project from '/Users/lee5hx/Works/java_projects/gaias/gaia/src/main' ...
[2017-03-21 15:42:34,071][DEBUG][Session       :  80] findProject            - finding project from '/Users/lee5hx/Works/java_projects/gaias/gaia/src' ...
[2017-03-21 15:42:34,071][DEBUG][Session       :  80] findProject            - finding project from '/Users/lee5hx/Works/java_projects/gaias/gaia' ...
[2017-03-21 15:42:34,071][DEBUG][Session       :  94] findProject            - find mvn project /Users/lee5hx/Works/java_projects/gaias/gaia/pom.xml
[2017-03-21 15:42:34,115][DEBUG][Config        :  57] <init>                 - home:/Users/lee5hx/emacs-confs/lee5hx/meghanada
[2017-03-21 15:42:34,115][DEBUG][Config        :  58] <init>                 - java-home:/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre
[2017-03-21 15:42:34,115][DEBUG][Config        :  59] <init>                 - java-version:1.8
[2017-03-21 15:42:34,115][DEBUG][Config        :  60] <init>                 - user-home:/Users/lee5hx
[2017-03-21 15:42:34,115][DEBUG][Config        :  61] <init>                 - project-root-dir:/Users/lee5hx/Works/java_projects/gaias/gaia
[2017-03-21 15:42:34,115][DEBUG][Config        :  62] <init>                 - fast-boot:true
[2017-03-21 15:42:34,116][DEBUG][Config        :  63] <init>                 - class-fuzzy-search:false
[2017-03-21 15:42:34,388][DEBUG][MavenProject  : 156] runMvn                 - RUN cmd: mvn dependency:resolve
[2017-03-21 15:42:34,397][ERROR][EmacsServer   :  70] startServer            - Catching
meghanada.project.ProjectParseException: java.io.IOException: Cannot run program "mvn" (in directory "/Users/lee5hx/Works/java_projects/gaias/gaia"): error=2, No such file or directory
	at meghanada.project.maven.MavenProject.parseProject(MavenProject.java:134) ~[meghanada-0.7.0.jar:?]
	at meghanada.session.Session.loadProject(Session.java:165) ~[meghanada-0.7.0.jar:?]
	at meghanada.session.Session.findProject(Session.java:95) ~[meghanada-0.7.0.jar:?]
	at meghanada.session.Session.createSession(Session.java:71) ~[meghanada-0.7.0.jar:?]
	at meghanada.session.Session.createSession(Session.java:66) ~[meghanada-0.7.0.jar:?]
	at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:65) [meghanada-0.7.0.jar:?]
	at meghanada.Main.main(Main.java:116) [meghanada-0.7.0.jar:?]
Caused by: java.io.IOException: Cannot run program "mvn" (in directory "/Users/lee5hx/Works/java_projects/gaias/gaia"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[?:1.8.0_111]
	at meghanada.project.maven.MavenProject.runMvn(MavenProject.java:159) ~[meghanada-0.7.0.jar:?]
	at meghanada.project.maven.MavenProject.parseProject(MavenProject.java:73) ~[meghanada-0.7.0.jar:?]
	... 6 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method) ~[?:1.8.0_111]
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247) ~[?:1.8.0_111]
	at java.lang.ProcessImpl.start(ProcessImpl.java:134) ~[?:1.8.0_111]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[?:1.8.0_111]
	at meghanada.project.maven.MavenProject.runMvn(MavenProject.java:159) ~[meghanada-0.7.0.jar:?]
	at meghanada.project.maven.MavenProject.parseProject(MavenProject.java:73) ~[meghanada-0.7.0.jar:?]
	... 6 more
[2017-03-21 15:42:34,402][INFO ][Main          :  43] lambda$main$1          - shutdown server

## 2. My Project Directory
![image](https://cloud.githubusercontent.com/assets/1617228/24137173/939920dc-0e4d-11e7-8fef-91f9284401bf.png)

**Comment by mopemope** [comment]
@lee5hx I guess, Maven command is not include your `$PATH`. Please add `mvn` command to `$PATH`, or set environment value `MEGHANADA_MAVEN_PATH` .

```
export MEGHANADA_MAVEN_PATH=<your maven home>/bin/mvn
```

**Comment by lee5hx** [comment]
Thanks, you guessed right.
My emacs environment $PATH no included  mvn command;

add init.el in the `exec-path-from-shell-initialize`
