### ISSUE TITLE
<M-.> showDeclaration java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by lee5hx** [mopemope/meghanada-server#11]
After I press the < m - .> show Declaration , emacs crash, 100% CPU.

I want to goto declaration interface.
![image](https://cloud.githubusercontent.com/assets/1617228/24287057/ee42947a-10b2-11e7-8f46-db810162d3b3.png)

it's interface.
![image](https://cloud.githubusercontent.com/assets/1617228/24287031/c93ca846-10b2-11e7-802c-55e6e40b77c2.png)

## server.log
[2017-03-24 16:36:01,051][ERROR][CommandHandler: 288] showDeclaration        - Catching
java.lang.NullPointerException: null
	at meghanada.utils.ClassNameUtils.vaArgsToArray(ClassNameUtils.java:435) ~[meghanada-0.7.0.jar:?]
	at meghanada.utils.ClassName.<init>(ClassName.java:16) ~[meghanada-0.7.0.jar:?]
	at meghanada.reflect.asm.CachedASMReflector.reflect(CachedASMReflector.java:342) ~[meghanada-0.7.0.jar:?]
	at meghanada.reflect.asm.CachedASMReflector.reflectMethodStream(CachedASMReflector.java:376) ~[meghanada-0.7.0.jar:?]
	at meghanada.docs.declaration.DeclarationSearcher.lambda$searchMethodCall$7(DeclarationSearcher.java:120) ~[meghanada-0.7.0.jar:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_111]
	at meghanada.docs.declaration.DeclarationSearcher.searchMethodCall(DeclarationSearcher.java:115) ~[meghanada-0.7.0.jar:?]
	at meghanada.docs.declaration.DeclarationSearcher.lambda$null$12(DeclarationSearcher.java:218) ~[meghanada-0.7.0.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_111]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351) ~[?:1.8.0_111]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_111]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_111]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_111]
	at meghanada.docs.declaration.DeclarationSearcher.lambda$searchDeclaration$13(DeclarationSearcher.java:220) ~[meghanada-0.7.0.jar:?]
	at java.util.Optional.flatMap(Optional.java:241) ~[?:1.8.0_111]
	at meghanada.docs.declaration.DeclarationSearcher.searchDeclaration(DeclarationSearcher.java:217) ~[meghanada-0.7.0.jar:?]
	at meghanada.session.Session.showDeclaration(Session.java:595) ~[meghanada-0.7.0.jar:?]
	at meghanada.server.CommandHandler.showDeclaration(CommandHandler.java:281) ~[meghanada-0.7.0.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$17(EmacsServer.java:245) ~[meghanada-0.7.0.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-0.7.0.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-0.7.0.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-0.7.0.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:277) ~[meghanada-0.7.0.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$2(EmacsServer.java:125) ~[meghanada-0.7.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[2017-03-24 16:36:01,059][ERROR][EmacsServer   : 138] lambda$acceptConnectio - Catching

**Comment by lee5hx** [comment]
I try to this commit, problem seems to be solved! thanks~
