### ISSUE TITLE
java.nio.file.AccessDeniedException

### ISSUE THREAD

**Issue by hughwilliams94** [mopemope/meghanada-server#128]
When I run `java -jar meghanada-1.3.0.jar` (or start the server via emacs), the server seems to start but then sends the following exception (and no commands in emacs seem to work):

```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[INFO ][Main      :  54] use java home: /usr/lib/jvm/java-11-openjdk
[INFO ][Main      :  55] use java runtime: OpenJDK Runtime Environment 11.0.6+10
[INFO ][Main      :  59] use java vm: OpenJDK 64-Bit Server VM 11.0.6+10
[INFO ][Main      : 151] Meghanada-Server Version:1.3.0-8f2803c
[ERROR][EmacsServe: 374] Catching
java.nio.file.AccessDeniedException: /home/hugh/.cache/dconf
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:432) ~[?:?]
	at java.nio.file.Files.newDirectoryStream(Files.java:471) ~[?:?]
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:300) ~[?:?]
	at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:373) ~[?:?]
	at java.nio.file.Files.walkFileTree(Files.java:2760) ~[?:?]
	at java.nio.file.Files.walkFileTree(Files.java:2796) ~[?:?]
	at meghanada.utils.FileUtils.findProjectID(FileUtils.java:211) ~[meghanada-1.3.0.jar:?]
	at meghanada.session.Session.loadProject(Session.java:181) ~[meghanada-1.3.0.jar:?]
	at meghanada.session.Session.findProject(Session.java:138) ~[meghanada-1.3.0.jar:?]
	at meghanada.session.Session.createSession(Session.java:110) ~[meghanada-1.3.0.jar:?]
	at meghanada.session.Session.createSession(Session.java:104) ~[meghanada-1.3.0.jar:?]
	at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:359) [meghanada-1.3.0.jar:?]
	at meghanada.Main.main(Main.java:153) [meghanada-1.3.0.jar:?]
```

Anything I can do to debug? It seems the problem seems to be that there are files in my home directory that do not belong to my user (they are build files from my package manager I think).

**Comment by Naheel-Azawy** [comment]
Same here
