### ISSUE TITLE
Go to definition crashes server

### ISSUE THREAD

**Issue by rgrinberg** [mopemope/meghanada-server#13]
When I do `meghanada-jump-declaration` on some idenifiers. For example:

https://github.com/mopemope/meghanada-server/blob/master/src/main/java/meghanada/server/CommandHandler.java#L58

That causes the server to crash.

**Comment by mopemope** [comment]
@rgrinberg  I couldn't reproduce it. Could you tell me server-log ?

**Comment by rgrinberg** [comment]
Yeah, I'd like to help out. How do I find this server-log?

**Comment by mopemope** [comment]
@rgrinberg Please check `*meghanada-server-log*` buffer.

**Comment by rgrinberg** [comment]
Here's the stack trace. Thanks again for the  patience.

```
com.github.javaparser.ParseProblemException: (line 13,col 47) Parse error. Found  "Inner2" <IDENTIFIER>, expected one of  "!=" "%" "%=" "&" "&&" "&=" "*" "*=" "+" "+=" "," "-" "-=" "->" "/" "/=" "::" ";" "<" "<<=" "<=" "=" "==" ">" ">=" ">>=" ">>>=" "?" "^" "^=" "instanceof" "|" "|=" "||"
Problem stacktrace : 
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:9908)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:9764)
  com.github.javaparser.GeneratedJavaParser.FieldDeclaration(GeneratedJavaParser.java:1073)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBodyDeclaration(GeneratedJavaParser.java:1000)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBody(GeneratedJavaParser.java:927)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceDeclaration(GeneratedJavaParser.java:580)
  com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:339)
  com.github.javaparser.JavaParser.parse(JavaParser.java:123)
  com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:386)
  com.github.javaparser.JavaParser.parse(JavaParser.java:247)
  meghanada.location.LocationSearcher.searchLocationFromFile(LocationSearcher.java:91)
  meghanada.location.LocationSearcher.searchLocationFromDecompileFile(LocationSearcher.java:467)
  meghanada.location.LocationSearcher.lambda$getLocationFromSrcOrDecompile$20(LocationSearcher.java:413)
  meghanada.utils.FunctionUtils.lambda$wrapIO$1(FunctionUtils.java:24)
  java.util.Optional.orElseGet(Optional.java:267)
  meghanada.location.LocationSearcher.getLocationFromSrcOrDecompile(LocationSearcher.java:412)
  meghanada.location.LocationSearcher.searchFromDependency(LocationSearcher.java:396)
  meghanada.location.LocationSearcher.lambda$null$6(LocationSearcher.java:248)
  meghanada.utils.FunctionUtils.lambda$wrapIO$1(FunctionUtils.java:24)
  java.util.Optional.orElseGet(Optional.java:267)
  meghanada.location.LocationSearcher.lambda$null$7(LocationSearcher.java:247)
  meghanada.utils.FunctionUtils.lambda$wrapIO$1(FunctionUtils.java:24)
  java.util.Optional.orElseGet(Optional.java:267)
  meghanada.location.LocationSearcher.lambda$null$8(LocationSearcher.java:242)
  java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
  java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
  java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
  java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
  java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
  java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
  java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
  java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
  meghanada.location.LocationSearcher.lambda$searchMethodCall$9(LocationSearcher.java:251)
  java.util.Optional.flatMap(Optional.java:241)
  meghanada.location.LocationSearcher.searchMethodCall(LocationSearcher.java:224)
  meghanada.location.LocationSearcher.lambda$searchDeclarationLocation$3(LocationSearcher.java:203)
  java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
  java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
  java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
  java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
  java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
  java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
  java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
  java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
  meghanada.location.LocationSearcher.searchDeclarationLocation(LocationSearcher.java:205)
  meghanada.session.Session.jumpDeclaration(Session.java:577)
  meghanada.server.CommandHandler.jumpDeclaration(CommandHandler.java:196)
  meghanada.server.emacs.EmacsServer.lambda$dispatch$16(EmacsServer.java:239)
  com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45)
  com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40)
  com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118)
  meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:277)
  meghanada.server.emacs.EmacsServer.lambda$acceptConnection$2(EmacsServer.java:125)
  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)

	at com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:390) ~[meghanada-0.7.3.jar:?]
	at com.github.javaparser.JavaParser.parse(JavaParser.java:247) ~[meghanada-0.7.3.jar:?]
	at meghanada.location.LocationSearcher.searchLocationFromFile(LocationSearcher.java:91) ~[meghanada-0.7.3.jar:?]
	at meghanada.location.LocationSearcher.searchLocationFromDecompileFile(LocationSearcher.java:467) ~[meghanada-0.7.3.jar:?]
	at meghanada.location.LocationSearcher.lambda$getLocationFromSrcOrDecompile$20(LocationSearcher.java:413) ~[meghanada-0.7.3.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIO$1(FunctionUtils.java:24) ~[meghanada-0.7.3.jar:?]
	at java.util.Optional.orElseGet(Optional.java:267) ~[?:1.8.0_121]
	at meghanada.location.LocationSearcher.getLocationFromSrcOrDecompile(LocationSearcher.java:412) ~[meghanada-0.7.3.jar:?]
	at meghanada.location.LocationSearcher.searchFromDependency(LocationSearcher.java:396) ~[meghanada-0.7.3.jar:?]
	at meghanada.location.LocationSearcher.lambda$null$6(LocationSearcher.java:248) ~[meghanada-0.7.3.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIO$1(FunctionUtils.java:24) ~[meghanada-0.7.3.jar:?]
	at java.util.Optional.orElseGet(Optional.java:267) ~[?:1.8.0_121]
	at meghanada.location.LocationSearcher.lambda$null$7(LocationSearcher.java:247) ~[meghanada-0.7.3.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIO$1(FunctionUtils.java:24) ~[meghanada-0.7.3.jar:?]
	at java.util.Optional.orElseGet(Optional.java:267) ~[?:1.8.0_121]
	at meghanada.location.LocationSearcher.lambda$null$8(LocationSearcher.java:242) ~[meghanada-0.7.3.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_121]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_121]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_121]
	at meghanada.location.LocationSearcher.lambda$searchMethodCall$9(LocationSearcher.java:251) ~[meghanada-0.7.3.jar:?]
	at java.util.Optional.flatMap(Optional.java:241) ~[?:1.8.0_121]
	at meghanada.location.LocationSearcher.searchMethodCall(LocationSearcher.java:224) ~[meghanada-0.7.3.jar:?]
	at meghanada.location.LocationSearcher.lambda$searchDeclarationLocation$3(LocationSearcher.java:203) ~[meghanada-0.7.3.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_121]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_121]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_121]
	at meghanada.location.LocationSearcher.searchDeclarationLocation(LocationSearcher.java:205) ~[meghanada-0.7.3.jar:?]
	at meghanada.session.Session.jumpDeclaration(Session.java:577) ~[meghanada-0.7.3.jar:?]
	at meghanada.server.CommandHandler.jumpDeclaration(CommandHandler.java:196) ~[meghanada-0.7.3.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$16(EmacsServer.java:239) ~[meghanada-0.7.3.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-0.7.3.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-0.7.3.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-0.7.3.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:277) ~[meghanada-0.7.3.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$2(EmacsServer.java:125) ~[meghanada-0.7.3.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[2017-04-07 09:41:57,623][ERROR][EmacsServer   : 138] lambda$acceptConnectio - Catching
meghanada.server.CommandException: com.github.javaparser.ParseProblemException: (line 13,col 47) Parse error. Found  "Inner2" <IDENTIFIER>, expected one of  "!=" "%" "%=" "&" "&&" "&=" "*" "*=" "+" "+=" "," "-" "-=" "->" "/" "/=" "::" ";" "<" "<<=" "<=" "=" "==" ">" ">=" ">>=" ">>>=" "?" "^" "^=" "instanceof" "|" "|=" "||"
Problem stacktrace : 
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:9908)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:9764)
  com.github.javaparser.GeneratedJavaParser.FieldDeclaration(GeneratedJavaParser.java:1073)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBodyDeclaration(GeneratedJavaParser.java:1000)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBody(GeneratedJavaParser.java:927)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceDeclaration(GeneratedJavaParser.java:580)
  com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:339)
  com.github.javaparser.JavaParser.parse(JavaParser.java:123)
  com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:386)
  com.github.javaparser.JavaParser.parse(JavaParser.java:247)
  meghanada.location.LocationSearcher.searchLocationFromFile(LocationSearcher.java:91)
  meghanada.location.LocationSearcher.searchLocationFromDecompileFile(LocationSearcher.java:467)
  meghanada.location.LocationSearcher.lambda$getLocationFromSrcOrDecompile$20(LocationSearcher.java:413)
  meghanada.utils.FunctionUtils.lambda$wrapIO$1(FunctionUtils.java:24)
  java.util.Optional.orElseGet(Optional.java:267)
  meghanada.location.LocationSearcher.getLocationFromSrcOrDecompile(LocationSearcher.java:412)
  meghanada.location.LocationSearcher.searchFromDependency(LocationSearcher.java:396)
  meghanada.location.LocationSearcher.lambda$null$6(LocationSearcher.java:248)
  meghanada.utils.FunctionUtils.lambda$wrapIO$1(FunctionUtils.java:24)
  java.util.Optional.orElseGet(Optional.java:267)
  meghanada.location.LocationSearcher.lambda$null$7(LocationSearcher.java:247)
  meghanada.utils.FunctionUtils.lambda$wrapIO$1(FunctionUtils.java:24)
  java.util.Optional.orElseGet(Optional.java:267)
  meghanada.location.LocationSearcher.lambda$null$8(LocationSearcher.java:242)
  java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
  java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
  java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
  java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
  java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
  java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
  java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
  java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
  meghanada.location.LocationSearcher.lambda$searchMethodCall$9(LocationSearcher.java:251)
  java.util.Optional.flatMap(Optional.java:241)
  meghanada.location.LocationSearcher.searchMethodCall(LocationSearcher.java:224)
  meghanada.location.LocationSearcher.lambda$searchDeclarationLocation$3(LocationSearcher.java:203)
  java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
  java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
  java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
  java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
  java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
  java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
  java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
  java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
  meghanada.location.LocationSearcher.searchDeclarationLocation(LocationSearcher.java:205)
  meghanada.session.Session.jumpDeclaration(Session.java:577)
  meghanada.server.CommandHandler.jumpDeclaration(CommandHandler.java:196)
  meghanada.server.emacs.EmacsServer.lambda$dispatch$16(EmacsServer.java:239)
  com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45)
  com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40)
  com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118)
  meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:277)
  meghanada.server.emacs.EmacsServer.lambda$acceptConnection$2(EmacsServer.java:125)
  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)

	at meghanada.server.CommandHandler.jumpDeclaration(CommandHandler.java:203) ~[meghanada-0.7.3.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$16(EmacsServer.java:239) ~[meghanada-0.7.3.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-0.7.3.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-0.7.3.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-0.7.3.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:277) ~[meghanada-0.7.3.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$2(EmacsServer.java:125) ~[meghanada-0.7.3.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: com.github.javaparser.ParseProblemException: (line 13,col 47) Parse error. Found  "Inner2" <IDENTIFIER>, expected one of  "!=" "%" "%=" "&" "&&" "&=" "*" "*=" "+" "+=" "," "-" "-=" "->" "/" "/=" "::" ";" "<" "<<=" "<=" "=" "==" ">" ">=" ">>=" ">>>=" "?" "^" "^=" "instanceof" "|" "|=" "||"
Problem stacktrace : 
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:9908)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:9764)
  com.github.javaparser.GeneratedJavaParser.FieldDeclaration(GeneratedJavaParser.java:1073)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBodyDeclaration(GeneratedJavaParser.java:1000)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBody(GeneratedJavaParser.java:927)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceDeclaration(GeneratedJavaParser.java:580)
  com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:339)
  com.github.javaparser.JavaParser.parse(JavaParser.java:123)
  com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:386)
  com.github.javaparser.JavaParser.parse(JavaParser.java:247)
  meghanada.location.LocationSearcher.searchLocationFromFile(LocationSearcher.java:91)
  meghanada.location.LocationSearcher.searchLocationFromDecompileFile(LocationSearcher.java:467)
  meghanada.location.LocationSearcher.lambda$getLocationFromSrcOrDecompile$20(LocationSearcher.java:413)
  meghanada.utils.FunctionUtils.lambda$wrapIO$1(FunctionUtils.java:24)
  java.util.Optional.orElseGet(Optional.java:267)
  meghanada.location.LocationSearcher.getLocationFromSrcOrDecompile(LocationSearcher.java:412)
  meghanada.location.LocationSearcher.searchFromDependency(LocationSearcher.java:396)
  meghanada.location.LocationSearcher.lambda$null$6(LocationSearcher.java:248)
  meghanada.utils.FunctionUtils.lambda$wrapIO$1(FunctionUtils.java:24)
  java.util.Optional.orElseGet(Optional.java:267)
  meghanada.location.LocationSearcher.lambda$null$7(LocationSearcher.java:247)
  meghanada.utils.FunctionUtils.lambda$wrapIO$1(FunctionUtils.java:24)
  java.util.Optional.orElseGet(Optional.java:267)
  meghanada.location.LocationSearcher.lambda$null$8(LocationSearcher.java:242)
  java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
  java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
  java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
  java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
  java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
  java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
  java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
  java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
  meghanada.location.LocationSearcher.lambda$searchMethodCall$9(LocationSearcher.java:251)
  java.util.Optional.flatMap(Optional.java:241)
  meghanada.location.LocationSearcher.searchMethodCall(LocationSearcher.java:224)
  meghanada.location.LocationSearcher.lambda$searchDeclarationLocation$3(LocationSearcher.java:203)
  java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
  java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
  java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
  java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
  java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
  java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
  java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
  java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
  meghanada.location.LocationSearcher.searchDeclarationLocation(LocationSearcher.java:205)
  meghanada.session.Session.jumpDeclaration(Session.java:577)
  meghanada.server.CommandHandler.jumpDeclaration(CommandHandler.java:196)
  meghanada.server.emacs.EmacsServer.lambda$dispatch$16(EmacsServer.java:239)
  com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45)
  com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40)
  com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118)
  meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:277)
  meghanada.server.emacs.EmacsServer.lambda$acceptConnection$2(EmacsServer.java:125)
  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)

	at com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:390) ~[meghanada-0.7.3.jar:?]
	at com.github.javaparser.JavaParser.parse(JavaParser.java:247) ~[meghanada-0.7.3.jar:?]
	at meghanada.location.LocationSearcher.searchLocationFromFile(LocationSearcher.java:91) ~[meghanada-0.7.3.jar:?]
	at meghanada.location.LocationSearcher.searchLocationFromDecompileFile(LocationSearcher.java:467) ~[meghanada-0.7.3.jar:?]
	at meghanada.location.LocationSearcher.lambda$getLocationFromSrcOrDecompile$20(LocationSearcher.java:413) ~[meghanada-0.7.3.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIO$1(FunctionUtils.java:24) ~[meghanada-0.7.3.jar:?]
	at java.util.Optional.orElseGet(Optional.java:267) ~[?:1.8.0_121]
	at meghanada.location.LocationSearcher.getLocationFromSrcOrDecompile(LocationSearcher.java:412) ~[meghanada-0.7.3.jar:?]
	at meghanada.location.LocationSearcher.searchFromDependency(LocationSearcher.java:396) ~[meghanada-0.7.3.jar:?]
	at meghanada.location.LocationSearcher.lambda$null$6(LocationSearcher.java:248) ~[meghanada-0.7.3.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIO$1(FunctionUtils.java:24) ~[meghanada-0.7.3.jar:?]
	at java.util.Optional.orElseGet(Optional.java:267) ~[?:1.8.0_121]
	at meghanada.location.LocationSearcher.lambda$null$7(LocationSearcher.java:247) ~[meghanada-0.7.3.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIO$1(FunctionUtils.java:24) ~[meghanada-0.7.3.jar:?]
	at java.util.Optional.orElseGet(Optional.java:267) ~[?:1.8.0_121]
	at meghanada.location.LocationSearcher.lambda$null$8(LocationSearcher.java:242) ~[meghanada-0.7.3.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_121]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_121]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_121]
	at meghanada.location.LocationSearcher.lambda$searchMethodCall$9(LocationSearcher.java:251) ~[meghanada-0.7.3.jar:?]
	at java.util.Optional.flatMap(Optional.java:241) ~[?:1.8.0_121]
	at meghanada.location.LocationSearcher.searchMethodCall(LocationSearcher.java:224) ~[meghanada-0.7.3.jar:?]
	at meghanada.location.LocationSearcher.lambda$searchDeclarationLocation$3(LocationSearcher.java:203) ~[meghanada-0.7.3.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_121]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_121]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_121]
	at meghanada.location.LocationSearcher.searchDeclarationLocation(LocationSearcher.java:205) ~[meghanada-0.7.3.jar:?]
	at meghanada.session.Session.jumpDeclaration(Session.java:577) ~[meghanada-0.7.3.jar:?]
	at meghanada.server.CommandHandler.jumpDeclaration(CommandHandler.java:196) ~[meghanada-0.7.3.jar:?]
	... 11 more
```

**Comment by rgrinberg** [comment]
Btw, I also ran the tests in this repo and got some failures. Perhaps it's related?

**Comment by mopemope** [comment]
@rgrinberg I recommend installing jdk's src.zip.

**Comment by rgrinberg** [comment]
@mopemope Thanks for the tip - that helped. The entire test suite passes for me and I'm able to go to the original sources when doing `meghanada-jump-declaration`. However, that particular method and others like still don't go to the correct declaration. In fact, they don't move the cursor at all. There's no error in the logs but it seems like the server is getting the request:

```
[2017-04-10 01:10:54,974][WARN ][Session       : 585] jumpDeclaration        - missing location path=/home/rgrinberg/reps/em/meghanada-server/src/main/java/meghanada/server/CommandHandler.java line=59 column=23 symbol=newLine
[2017-04-10 01:10:54,975][INFO ][EmacsServer   : 279] dispatch               - receive command [jd, /home/rgrinberg/reps/em/meghanada-server/src/main/java/meghanada/server/CommandHandler.java, 59, 23, newLine]. elapsed:3.006 ms

```

**Comment by mopemope** [comment]
@rgrinberg Please check latest version.
