### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by rgrinberg** [mopemope/meghanada-server#15]
I don't yet have  a consistent way to reproduce, but some stack traces are available:

```
[2017-04-14 13:20:32,284][INFO ][MavenProject  :  73] parseProject           - running maven. resolve dependencies ...
[2017-04-14 13:20:36,469][ERROR][Session       : 374] changeProject          - Catching
meghanada.project.ProjectParseException: meghanada.project.ProjectParseException: meghanada.project.ProjectParseException: java.io.IOException: Is a directory
	at meghanada.project.maven.MavenProject.parseProject(MavenProject.java:128) ~[meghanada-0.7.4.jar:?]
	at meghanada.session.Session.loadProject(Session.java:169) ~[meghanada-0.7.4.jar:?]
	at meghanada.session.Session.searchAndChangeProject(Session.java:266) ~[meghanada-0.7.4.jar:?]
	at meghanada.session.Session.changeProject(Session.java:364) ~[meghanada-0.7.4.jar:?]
	at meghanada.server.CommandHandler.changeProject(CommandHandler.java:43) ~[meghanada-0.7.4.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$3(EmacsServer.java:157) ~[meghanada-0.7.4.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-0.7.4.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-0.7.4.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-0.7.4.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:277) ~[meghanada-0.7.4.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$2(EmacsServer.java:125) ~[meghanada-0.7.4.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: meghanada.project.ProjectParseException: meghanada.project.ProjectParseException: java.io.IOException: Is a directory
	at meghanada.project.maven.POMParser.parsePom(POMParser.java:109) ~[meghanada-0.7.4.jar:?]
	at meghanada.project.maven.MavenProject.parseProject(MavenProject.java:93) ~[meghanada-0.7.4.jar:?]
	... 15 more
Caused by: meghanada.project.ProjectParseException: java.io.IOException: Is a directory
	at meghanada.project.maven.POMParser.parsePom(POMParser.java:109) ~[meghanada-0.7.4.jar:?]
	at meghanada.project.maven.POMParser.parsePom(POMParser.java:62) ~[meghanada-0.7.4.jar:?]
	at meghanada.project.maven.MavenProject.parseProject(MavenProject.java:93) ~[meghanada-0.7.4.jar:?]
	... 15 more
Caused by: java.io.IOException: Is a directory
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_121]
	at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46) ~[?:1.8.0_121]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_121]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[?:1.8.0_121]
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159) ~[?:1.8.0_121]
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65) ~[?:1.8.0_121]
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109) ~[?:1.8.0_121]
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103) ~[?:1.8.0_121]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[?:1.8.0_121]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:1.8.0_121]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:1.8.0_121]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[?:1.8.0_121]
	at java.io.BufferedReader.read1(BufferedReader.java:210) ~[?:1.8.0_121]
	at java.io.BufferedReader.read(BufferedReader.java:286) ~[?:1.8.0_121]
	at org.codehaus.plexus.util.xml.pull.MXParser.fillBuf(MXParser.java:3026) ~[meghanada-0.7.4.jar:?]
	at org.codehaus.plexus.util.xml.pull.MXParser.more(MXParser.java:3080) ~[meghanada-0.7.4.jar:?]
	at org.codehaus.plexus.util.xml.pull.MXParser.parseProlog(MXParser.java:1451) ~[meghanada-0.7.4.jar:?]
	at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1436) ~[meghanada-0.7.4.jar:?]
	at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1131) ~[meghanada-0.7.4.jar:?]
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:3849) ~[meghanada-0.7.4.jar:?]
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:595) ~[meghanada-0.7.4.jar:?]
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:609) ~[meghanada-0.7.4.jar:?]
	at meghanada.project.maven.POMParser.parsePom(POMParser.java:53) ~[meghanada-0.7.4.jar:?]
	at meghanada.project.maven.POMParser.parsePom(POMParser.java:62) ~[meghanada-0.7.4.jar:?]
	at meghanada.project.maven.MavenProject.parseProject(MavenProject.java:93) ~[meghanada-0.7.4.jar:?]
	... 15 more
[2017-04-14 13:20:36,475][INFO ][EmacsServer   : 279] dispatch               - receive command [pc, /home/rgrinberg/nci/protege/protege-launcher/src/main/java/org/protege/osgi/framework/BundleInfo.java]. elapsed:4.194 s
[2017-04-14 13:20:36,498][INFO ][Project       : 238] compileJava            - project lucene-search-plugin compile and analyze (java) 0 files. force:false elapsed:21.44 ms
[2017-04-14 13:20:36,499][INFO ][EmacsServer   : 279] dispatch               - receive command [di, /home/rgrinberg/nci/protege/protege-launcher/src/main/java/org/protege/osgi/framework/BundleInfo.java]. elapsed:23.77 ms
[2017-04-14 13:29:24,338][INFO ][EmacsServer   : 279] dispatch               - receive command [pc, /home/rgrinberg/nci/protege/protege-launcher/src/main/java/org/protege/osgi/framework/Parser.java]. elapsed:4.895 ms
[2017-04-14 13:29:24,377][INFO ][EmacsServer   : 279] dispatch               - receive command [di, /home/rgrinberg/nci/protege/protege-launcher/src/main/java/org/protege/osgi/framework/Parser.java]. elapsed:5.341 ms
[2017-04-14 13:29:24,889][INFO ][Config        : 114] timeItF                - create class index. read 60 jars. elapsed:551.4 ms
[2017-04-14 13:29:24,890][INFO ][CacheEventSubs:  51] analyze                - start analyze sources ...
[2017-04-14 13:29:24,891][INFO ][Config        : 114] timeItF                - analyzed and compiled. elapsed:96.94 μs
[2017-04-14 13:29:24,899][ERROR][Session       :  32] lambda$new$0           - null
java.lang.NullPointerException: null
	at meghanada.reflect.asm.CachedASMReflector.addClasspath(CachedASMReflector.java:160) ~[meghanada-0.7.4.jar:?]
	at meghanada.session.subscribe.CacheEventSubscriber.analyze(CacheEventSubscriber.java:68) ~[meghanada-0.7.4.jar:?]
	at meghanada.session.subscribe.CacheEventSubscriber.on(CacheEventSubscriber.java:34) ~[meghanada-0.7.4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[meghanada-0.7.4.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[meghanada-0.7.4.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [meghanada-0.7.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[2017-04-14 13:38:11,264][ERROR][Session       : 374] changeProject          - Catching
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[meghanada-0.7.4.jar:?]
	at meghanada.cache.GlobalCache.getSource(GlobalCache.java:176) ~[meghanada-0.7.4.jar:?]
	at meghanada.session.Session.changeProject(Session.java:370) ~[meghanada-0.7.4.jar:?]
	at meghanada.server.CommandHandler.changeProject(CommandHandler.java:43) ~[meghanada-0.7.4.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$3(EmacsServer.java:157) ~[meghanada-0.7.4.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-0.7.4.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-0.7.4.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-0.7.4.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:277) ~[meghanada-0.7.4.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$2(EmacsServer.java:125) ~[meghanada-0.7.4.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at meghanada.project.Project.parseFile(Project.java:323) ~[meghanada-0.7.4.jar:?]
	at meghanada.cache.JavaSourceLoader.load(JavaSourceLoader.java:109) ~[meghanada-0.7.4.jar:?]
	at meghanada.cache.JavaSourceLoader.load(JavaSourceLoader.java:22) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[meghanada-0.7.4.jar:?]
	... 17 more
[2017-04-14 13:38:11,265][INFO ][EmacsServer   : 279] dispatch               - receive command [pc, /home/rgrinberg/nci/protege/protege-launcher/src/main/java/org/protege/osgi/framework/SymbolicName.java]. elapsed:5.636 ms
[2017-04-14 13:38:11,282][INFO ][EmacsServer   : 279] dispatch               - receive command [di, /home/rgrinberg/nci/protege/protege-launcher/src/main/java/org/protege/osgi/framework/SymbolicName.java]. elapsed:1.510 ms
[2017-04-14 13:38:18,914][ERROR][CommandHandler: 288] showDeclaration        - Catching
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[meghanada-0.7.4.jar:?]
	at meghanada.cache.GlobalCache.getSource(GlobalCache.java:176) ~[meghanada-0.7.4.jar:?]
	at meghanada.utils.FileUtils.getSource(FileUtils.java:374) ~[meghanada-0.7.4.jar:?]
	at meghanada.docs.declaration.DeclarationSearcher.searchDeclaration(DeclarationSearcher.java:221) ~[meghanada-0.7.4.jar:?]
	at meghanada.session.Session.showDeclaration(Session.java:634) ~[meghanada-0.7.4.jar:?]
	at meghanada.server.CommandHandler.showDeclaration(CommandHandler.java:281) ~[meghanada-0.7.4.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$17(EmacsServer.java:245) ~[meghanada-0.7.4.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-0.7.4.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-0.7.4.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-0.7.4.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:277) ~[meghanada-0.7.4.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$2(EmacsServer.java:125) ~[meghanada-0.7.4.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at meghanada.project.Project.parseFile(Project.java:323) ~[meghanada-0.7.4.jar:?]
	at meghanada.cache.JavaSourceLoader.load(JavaSourceLoader.java:109) ~[meghanada-0.7.4.jar:?]
	at meghanada.cache.JavaSourceLoader.load(JavaSourceLoader.java:22) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[meghanada-0.7.4.jar:?]
	... 19 more
[2017-04-14 13:38:18,918][ERROR][EmacsServer   : 138] lambda$acceptConnectio - Catching
meghanada.server.CommandException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at meghanada.server.CommandHandler.showDeclaration(CommandHandler.java:289) ~[meghanada-0.7.4.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$17(EmacsServer.java:245) ~[meghanada-0.7.4.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-0.7.4.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-0.7.4.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-0.7.4.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:277) ~[meghanada-0.7.4.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$2(EmacsServer.java:125) ~[meghanada-0.7.4.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[meghanada-0.7.4.jar:?]
	at meghanada.cache.GlobalCache.getSource(GlobalCache.java:176) ~[meghanada-0.7.4.jar:?]
	at meghanada.utils.FileUtils.getSource(FileUtils.java:374) ~[meghanada-0.7.4.jar:?]
	at meghanada.docs.declaration.DeclarationSearcher.searchDeclaration(DeclarationSearcher.java:221) ~[meghanada-0.7.4.jar:?]
	at meghanada.session.Session.showDeclaration(Session.java:634) ~[meghanada-0.7.4.jar:?]
	at meghanada.server.CommandHandler.showDeclaration(CommandHandler.java:281) ~[meghanada-0.7.4.jar:?]
	... 11 more
Caused by: java.lang.NullPointerException
	at meghanada.project.Project.parseFile(Project.java:323) ~[meghanada-0.7.4.jar:?]
	at meghanada.cache.JavaSourceLoader.load(JavaSourceLoader.java:109) ~[meghanada-0.7.4.jar:?]
	at meghanada.cache.JavaSourceLoader.load(JavaSourceLoader.java:22) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[meghanada-0.7.4.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[meghanada-0.7.4.jar:?]
	at meghanada.cache.GlobalCache.getSource(GlobalCache.java:176) ~[meghanada-0.7.4.jar:?]
	at meghanada.utils.FileUtils.getSource(FileUtils.java:374) ~[meghanada-0.7.4.jar:?]
	at meghanada.docs.declaration.DeclarationSearcher.searchDeclaration(DeclarationSearcher.java:221) ~[meghanada-0.7.4.jar:?]
	at meghanada.session.Session.showDeclaration(Session.java:634) ~[meghanada-0.7.4.jar:?]
	at meghanada.server.CommandHandler.showDeclaration(CommandHandler.java:281) ~[meghanada-0.7.4.jar:?]
	... 11 more
[2017-04-14 13:38:18,920][INFO ][EmacsServer   : 145] lambda$acceptConnectio - client disconnect
```

**Comment by mopemope** [comment]
@rgrinberg Please check latest version.
