### ISSUE TITLE
Have meghanada completely separate gradle build for server and regular gradle invocations

### ISSUE THREAD

**Issue by dakrone** [mopemope/meghanada-server#16]
I've noticed that sometimes when I invoke `gradle` at the command line to run a test, or do something else, it seems to mess with the gradle that meghanada is running, cleaning up build files or something, which causes the server to crash.

Here's an example log I saw today:

```
java.io.UncheckedIOException: meghanada.project.ProjectParseException: java.lang.RuntimeException: org.gradle.tooling.BuildException: Could not fetch model of type 'IdeaProject' using Gradle distribution 'https://services.gradle.org/distributions/gradle-3.3-bin.zip'.
	at meghanada.project.ProjectDependency.getDependencyFilePath(ProjectDependency.java:148) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.subscribe.CacheEventSubscriber.lambda$analyze$3(CacheEventSubscriber.java:74) ~[meghanada-0.7.5.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_111]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_111]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_111]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_111]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_111]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_111]
	at meghanada.session.subscribe.CacheEventSubscriber.analyze(CacheEventSubscriber.java:73) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.subscribe.CacheEventSubscriber.on(CacheEventSubscriber.java:34) ~[meghanada-0.7.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[meghanada-0.7.5.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[meghanada-0.7.5.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [meghanada-0.7.5.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: meghanada.project.ProjectParseException: java.lang.RuntimeException: org.gradle.tooling.BuildException: Could not fetch model of type 'IdeaProject' using Gradle distribution 'https://services.gradle.org/distributions/gradle-3.3-bin.zip'.
	at meghanada.project.gradle.GradleProject.parseProject(GradleProject.java:104) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.Session.loadProject(Session.java:169) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.Session.findProject(Session.java:96) ~[meghanada-0.7.5.jar:?]
	at meghanada.project.ProjectDependency.getDependencyFilePath(ProjectDependency.java:130) ~[meghanada-0.7.5.jar:?]
	... 22 more
Caused by: java.lang.RuntimeException: org.gradle.tooling.BuildException: Could not fetch model of type 'IdeaProject' using Gradle distribution 'https://services.gradle.org/distributions/gradle-3.3-bin.zip'.
	at meghanada.config.Config.debugTimeItF(Config.java:123) ~[meghanada-0.7.5.jar:?]
	at meghanada.project.gradle.GradleProject.parseProject(GradleProject.java:86) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.Session.loadProject(Session.java:169) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.Session.findProject(Session.java:96) ~[meghanada-0.7.5.jar:?]
	at meghanada.project.ProjectDependency.getDependencyFilePath(ProjectDependency.java:130) ~[meghanada-0.7.5.jar:?]
	... 22 more
Caused by: org.gradle.tooling.BuildException: Could not fetch model of type 'IdeaProject' using Gradle distribution 'https://services.gradle.org/distributions/gradle-3.3-bin.zip'.
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:51) ~[meghanada-0.7.5.jar:?]
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29) ~[meghanada-0.7.5.jar:?]
	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:41) ~[meghanada-0.7.5.jar:?]
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57) ~[meghanada-0.7.5.jar:?]
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63) ~[meghanada-0.7.5.jar:?]
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46) ~[meghanada-0.7.5.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_111]
	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46) ~[meghanada-0.7.5.jar:?]
	at org.gradle.tooling.internal.consumer.DefaultModelBuilder.get(DefaultModelBuilder.java:50) ~[meghanada-0.7.5.jar:?]
	at org.gradle.tooling.internal.consumer.DefaultProjectConnection.getModel(DefaultProjectConnection.java:41) ~[meghanada-0.7.5.jar:?]
	at meghanada.project.gradle.GradleProject.lambda$parseProject$0(GradleProject.java:87) ~[meghanada-0.7.5.jar:?]
	at meghanada.config.Config.debugTimeItF(Config.java:121) ~[meghanada-0.7.5.jar:?]
	at meghanada.project.gradle.GradleProject.parseProject(GradleProject.java:86) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.Session.loadProject(Session.java:169) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.Session.findProject(Session.java:96) ~[meghanada-0.7.5.jar:?]
	at meghanada.project.ProjectDependency.getDependencyFilePath(ProjectDependency.java:130) ~[meghanada-0.7.5.jar:?]
	... 22 more
Caused by: org.gradle.internal.exceptions.LocationAwareException: Build file '/home/hinmanm/es/elasticsearch/benchmarks/build.gradle' line: 31
A problem occurred evaluating project ':benchmarks'.
	at org.gradle.initialization.DefaultExceptionAnalyser.transform(DefaultExceptionAnalyser.java:74) ~[?:?]
	at org.gradle.initialization.MultipleBuildFailuresExceptionAnalyser.transform(MultipleBuildFailuresExceptionAnalyser.java:47) ~[?:?]
	at org.gradle.initialization.StackTraceSanitizingExceptionAnalyser.transform(StackTraceSanitizingExceptionAnalyser.java:30) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:122) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher.getBuildAnalysis(DefaultGradleLauncher.java:107) ~[?:?]
	at org.gradle.launcher.exec.GradleBuildController.configure(GradleBuildController.java:79) ~[?:?]
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:52) ~[?:?]
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35) ~[?:?]
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:43) ~[?:?]
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:40) ~[?:?]
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169) ~[meghanada-0.7.5.jar:?]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106) ~[?:?]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56) ~[?:?]
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40) ~[?:?]
	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:75) ~[?:?]
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35) ~[?:?]
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41) ~[?:?]
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26) ~[?:?]
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75) ~[?:?]
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49) ~[?:?]
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44) ~[?:?]
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72) ~[?:?]
	at org.gradle.util.Swapper.swap(Swapper.java:38) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50) ~[?:?]
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297) ~[?:?]
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54) ~[meghanada-0.7.5.jar:?]
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40) ~[meghanada-0.7.5.jar:?]
Caused by: org.gradle.api.GradleScriptException: A problem occurred evaluating project ':benchmarks'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:92) ~[?:?]
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:176) ~[?:?]
	at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77) ~[?:?]
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:181) ~[?:?]
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39) ~[?:?]
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26) ~[?:?]
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34) ~[?:?]
	at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:70) ~[?:?]
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33) ~[?:?]
	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53) ~[?:?]
	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50) ~[?:?]
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169) ~[meghanada-0.7.5.jar:?]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106) ~[?:?]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61) ~[?:?]
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50) ~[?:?]
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:628) ~[?:?]
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:129) ~[?:?]
	at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35) ~[?:?]
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62) ~[?:?]
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:161) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:158) ~[?:?]
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169) ~[meghanada-0.7.5.jar:?]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106) ~[?:?]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:158) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher.getBuildAnalysis(DefaultGradleLauncher.java:107) ~[?:?]
	at org.gradle.launcher.exec.GradleBuildController.configure(GradleBuildController.java:79) ~[?:?]
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:52) ~[?:?]
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35) ~[?:?]
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:43) ~[?:?]
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:40) ~[?:?]
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169) ~[meghanada-0.7.5.jar:?]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106) ~[?:?]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56) ~[?:?]
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40) ~[?:?]
	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:75) ~[?:?]
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35) ~[?:?]
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41) ~[?:?]
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26) ~[?:?]
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75) ~[?:?]
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49) ~[?:?]
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44) ~[?:?]
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72) ~[?:?]
	at org.gradle.util.Swapper.swap(Swapper.java:38) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50) ~[?:?]
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297) ~[?:?]
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54) ~[meghanada-0.7.5.jar:?]
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40) ~[meghanada-0.7.5.jar:?]
Caused by: java.lang.NoClassDefFoundError: org/elasticsearch/gradle/BuildPlugin$_configureRepositories_closure6
	at org.elasticsearch.gradle.BuildPlugin.configureRepositories(BuildPlugin.groovy:304) ~[?:?]
	at org.elasticsearch.gradle.BuildPlugin$configureRepositories$1.callStatic(Unknown Source) ~[?:?]
	at org.elasticsearch.gradle.BuildPlugin.apply(BuildPlugin.groovy:77) ~[?:?]
	at org.elasticsearch.gradle.BuildPlugin.apply(BuildPlugin.groovy) ~[?:?]
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35) ~[?:?]
	at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43) ~[?:?]
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:139) ~[?:?]
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112) ~[?:?]
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:113) ~[?:?]
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36) ~[?:?]
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80) ~[?:?]
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136) ~[?:?]
	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:44) ~[?:?]
	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:34) ~[?:?]
	at org.gradle.api.Script$apply.callCurrent(Unknown Source) ~[?:?]
... etc
```

Is there a way to completely decouple the two so the two different gradle instances don't step on each other's toes? Is this because I'm using the gradle daemon?

**Comment by mopemope** [comment]
@dakrone Yes. It will always be reused. When gradle tooling api is used, gradle is always started in daemon mode.
Anyone have a good idea?

**Comment by mopemope** [comment]
@dakrone I experimentally tried to separate daemon process. Could you try the latest version?
