### ISSUE TITLE
OpenBSD Not Supported

### ISSUE THREAD

**Issue by lightningx10** [mopemope/meghanada-server#169]
When running on OpenBSD, is there any reason that this starts and crashes simply saying the following error:
```
[INFO ][Main      :  54] use java home: /usr/local/jdk-17
[INFO ][Main      :  55] use java runtime: OpenJDK Runtime Environment 17.0.1+12-1
[INFO ][Main      :  59] use java vm: OpenJDK 64-Bit Server VM 17.0.1+12-1
Exception in thread "main" java.lang.ExceptionInInitializerError
	at meghanada.Main.main(Main.java:66)
Caused by: java.lang.UnsupportedOperationException: Operating system not supported: 5
	at oshi.SystemInfo.getHardware(SystemInfo.java:144)
	at meghanada.telemetry.TelemetryUtils.<clinit>(TelemetryUtils.java:115)
	... 1 more
```
What is stopping this from working on OpenBSD?

**Comment by liar666** [comment]
+1

Is there any OS-specific code necessary to support Java in Emacs? I don't understand why you need to check the OS...
Plus, why would meghanada itself be written in Java (platform-independant language) if it would require platform-specific code?

**Comment by mopemope** [comment]
This is currently beyond my scope. Sorry about that!
