### ISSUE TITLE
request.modelResolver cannot be null

### ISSUE THREAD

**Issue by asqrd** [mopemope/meghanada-server#18]
Server is crashing with following error:

`[2017-05-11 23:30:37,767][INFO ][Main          : 114] main                   - Meghanada-Server Version:0.7.5-d441072
[2017-05-11 23:30:37,835][INFO ][MavenProject  :  73] parseProject           - running maven. resolve dependencies ...
[2017-05-11 23:30:39,866][ERROR][EmacsServer   :  70] startServer            - Catching
java.lang.NullPointerException: request.modelResolver cannot be null (parent POM org.springframework.boot:spring-boot-starter-parent:1.5.3.RELEASE and POM com.alexafshar:springangularone:0.0.1-SNAPSHOT (/home/asqrd/Work/code/java/springangularone/pom.xml))
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225) ~[meghanada-0.7.5.jar:?]
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1045) ~[meghanada-0.7.5.jar:?]
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:829) ~[meghanada-0.7.5.jar:?]
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:331) ~[meghanada-0.7.5.jar:?]
	at meghanada.project.maven.POMParser.parsePom(POMParser.java:64) ~[meghanada-0.7.5.jar:?]
	at meghanada.project.maven.MavenProject.parseProject(MavenProject.java:93) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.Session.loadProject(Session.java:169) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.Session.findProject(Session.java:99) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.Session.createSession(Session.java:75) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.Session.createSession(Session.java:70) ~[meghanada-0.7.5.jar:?]
	at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:65) [meghanada-0.7.5.jar:?]
	at meghanada.Main.main(Main.java:116) [meghanada-0.7.5.jar:?]
[2017-05-11 23:30:39,869][INFO ][Main          :  43] lambda$main$1          - shutdown server`

I am testing a small spring-boot app, here is the pom.xml:
```

	<groupId>com.alexafshar</groupId>
	<artifactId>springangularone</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>springangularone</name>
	<description>Demo project for Spring Boot</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.3.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>

		<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>angularjs</artifactId>
			<version>1.6.2</version>
		</dependency>

		<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>webjars-locator</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>

			</plugin>
			<plugin>
			  <groupId>org.ensime.maven.plugins</groupId>
			  <artifactId>ensime-maven</artifactId>
			  <version>1.1.0</version>
			</plugin>
		</plugins>
	</build>


</project>
`
Gradle is working fantastic (last update really sped up indexing, so cheers for that!), so I am also including a snippet of my zshrc file:
`export MEGHANADA_MAVEN_PATH=$HOME/.sdkman/candidates/maven/current/bin/mvn
export PATH=$PATH:$MEGHANADA_MAVEN_PATH`

Please let me know if anyone has similiar issue, or you can identify mine. And thanks for this project, It is my best bet for kicking intellij to the curb!

**Comment by evnm** [comment]
I'm getting a similar error complaining that both `request.workspaceModelResolver` and `request.modelResolver` are null:

```
Listening for transport dt_socket at address: 5005
[2017-05-14 09:34:57,918][DEBUG][Main          :  73] main                   - set verbose flag(DEBUG)
[2017-05-14 09:34:57,921][DEBUG][Main          : 111] main                   - set port:55555, projectRoot:./, output:sexp
[2017-05-14 09:34:57,921][INFO ][Main          : 114] main                   - Meghanada-Server Version:0.7.5-d441072
[2017-05-14 09:34:57,935][DEBUG][Session       :  84] findProject            - finding project from '/Users/evanm/workspace/whiskerlabs/aphid/aphid-server/src/main/java/com/whiskerlabs/aphid/resources' ...
[2017-05-14 09:34:57,936][DEBUG][Session       :  84] findProject            - finding project from '/Users/evanm/workspace/whiskerlabs/aphid/aphid-server/src/main/java/com/whiskerlabs/aphid' ...
[2017-05-14 09:34:57,936][DEBUG][Session       :  84] findProject            - finding project from '/Users/evanm/workspace/whiskerlabs/aphid/aphid-server/src/main/java/com/whiskerlabs' ...
[2017-05-14 09:34:57,936][DEBUG][Session       :  84] findProject            - finding project from '/Users/evanm/workspace/whiskerlabs/aphid/aphid-server/src/main/java/com' ...
[2017-05-14 09:34:57,936][DEBUG][Session       :  84] findProject            - finding project from '/Users/evanm/workspace/whiskerlabs/aphid/aphid-server/src/main/java' ...
[2017-05-14 09:34:57,936][DEBUG][Session       :  84] findProject            - finding project from '/Users/evanm/workspace/whiskerlabs/aphid/aphid-server/src/main' ...
[2017-05-14 09:34:57,936][DEBUG][Session       :  84] findProject            - finding project from '/Users/evanm/workspace/whiskerlabs/aphid/aphid-server/src' ...
[2017-05-14 09:34:57,937][DEBUG][Session       :  84] findProject            - finding project from '/Users/evanm/workspace/whiskerlabs/aphid/aphid-server' ...
[2017-05-14 09:34:57,937][DEBUG][Session       :  98] findProject            - find mvn project /Users/evanm/workspace/whiskerlabs/aphid/aphid-server/pom.xml
[2017-05-14 09:34:58,005][DEBUG][Config        :  57] <init>                 - home:/Users/evanm/.meghanada
[2017-05-14 09:34:58,005][DEBUG][Config        :  58] <init>                 - java-home:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre
[2017-05-14 09:34:58,005][DEBUG][Config        :  59] <init>                 - java-version:1.8
[2017-05-14 09:34:58,005][DEBUG][Config        :  60] <init>                 - user-home:/Users/evanm
[2017-05-14 09:34:58,005][DEBUG][Config        :  61] <init>                 - project-root-dir:/Users/evanm/workspace/whiskerlabs/aphid/aphid-server
[2017-05-14 09:34:58,006][DEBUG][Config        :  62] <init>                 - fast-boot:true
[2017-05-14 09:34:58,006][DEBUG][Config        :  63] <init>                 - class-fuzzy-search:false
[2017-05-14 09:34:58,080][INFO ][MavenProject  :  73] parseProject           - running maven. resolve dependencies ...
[2017-05-14 09:34:58,081][DEBUG][MavenProject  : 150] runMvn                 - RUN cmd: mvn dependency:resolve dependency:sources dependency:build-classpath -Dmdep.outputFile=/private/var/folders/zd/k9r90x_13ml9bk21vmtrpsqh0000gn/T/meghanada-maven-classpath8047269324322505686.log
[2017-05-14 09:35:24,478][ERROR][EmacsServer   :  70] startServer            - Catching
java.lang.NullPointerException: request.workspaceModelResolver and request.modelResolver cannot be null (parent POM com.whiskerlabs:whiskerlabs-bom:0.0.1-SNAPSHOT and POM com.whiskerlabs:aphid-server:0.0.1-SNAPSHOT (/Users/evanm/workspace/whiskerlabs/aphid/aphid-server/pom.xml))
	at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement(DefaultModelBuilder.java:1217) ~[meghanada-0.7.5.jar:?]
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:457) ~[meghanada-0.7.5.jar:?]
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:423) ~[meghanada-0.7.5.jar:?]
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:413) ~[meghanada-0.7.5.jar:?]
	at meghanada.project.maven.POMParser.parsePom(POMParser.java:64) ~[meghanada-0.7.5.jar:?]
	at meghanada.project.maven.MavenProject.parseProject(MavenProject.java:93) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.Session.loadProject(Session.java:169) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.Session.findProject(Session.java:99) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.Session.createSession(Session.java:75) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.Session.createSession(Session.java:70) ~[meghanada-0.7.5.jar:?]
	at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:65) [meghanada-0.7.5.jar:?]
	at meghanada.Main.main(Main.java:116) [meghanada-0.7.5.jar:?]
[2017-05-14 09:35:24,482][INFO ][Main          :  43] lambda$main$1          - shutdown server
```

The project in question (`aphid-server` in the above output) is contained with a monorepo that has a parent pom (`whiskerlabs-bom`).

**Comment by mopemope** [comment]
@asqrd Thank you for your report. Sorry. It does not support to parent pom yet.

**Comment by asqrd** [comment]
@mopemope Thanks for your reply. Great job so far, do you accept pull-requests? Maybe I can take a stab at it in the coming weeks. Would love to see support for this. Thanks.

**Comment by mopemope** [comment]
@asqrd Contributions are extremely welcome! Thanks.

**Comment by asqrd** [comment]
Ok, will do thanks.
