### ISSUE TITLE
Server craches with NullPointerException with incomplete source files

### ISSUE THREAD

**Issue by terlar** [mopemope/meghanada-server#20]
When I am developing a function and adding a new one and the syntax is temporarily wrong (because I am still editing) it seems the server is crashing with the following error:

```
Caused by: java.lang.NullPointerException
	at meghanada.project.Project.parseFile(Project.java:323) ~[meghanada-0.7.5.jar:?]
	at meghanada.cache.JavaSourceLoader.load(JavaSourceLoader.java:109) ~[meghanada-0.7.5.jar:?]
	at meghanada.cache.JavaSourceLoader.load(JavaSourceLoader.java:22) ~[meghanada-0.7.5.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[meghanada-0.7.5.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[meghanada-0.7.5.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[meghanada-0.7.5.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[meghanada-0.7.5.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[meghanada-0.7.5.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[meghanada-0.7.5.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[meghanada-0.7.5.jar:?]
	at meghanada.cache.GlobalCache.getSource(GlobalCache.java:176) ~[meghanada-0.7.5.jar:?]
	at meghanada.utils.FileUtils.getSource(FileUtils.java:374) ~[meghanada-0.7.5.jar:?]
	at meghanada.docs.declaration.DeclarationSearcher.searchDeclaration(DeclarationSearcher.java:221) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.Session.showDeclaration(Session.java:634) ~[meghanada-0.7.5.jar:?]
	at meghanada.server.CommandHandler.showDeclaration(CommandHandler.java:281) ~[meghanada-0.7.5.jar:?]
	... 11 more
[2017-05-14 10:31:18,587][INFO ][EmacsServer   : 145] lambda$acceptConnectio - client disconnect
[2017-05-14 10:25:03,515][INFO ][Main          : 114] main                   - Meghanada-Server Version:0.7.5-d441072
```

Is this a bug or is it not feasible to have it run during editing, it might be my emacs settings continuously saving the file when I pause for a bit.

**Comment by mopemope** [comment]
@terlar Thank you for your report. you are using gradle ?

**Comment by mopemope** [comment]
@terlar Please check latest version.

**Comment by terlar** [comment]
@mopemope Sorry for not getting back to you, I was a bit busy recently. This project is not `gradle` it is using `sbt` for dependencies, but I have manually created the `.meghanada.conf` with the dependencies.

Like this:
```
compile-source = "1.8"
compile-target = "1.8"

sources = ["src/main/java"]
resources = ["src/main/resources"]
test-sources = ["src/test/java"]

dependencies = ["/home/terje/.ivy2/cache/com.secret.service-registry/core/jars/core-0.5.3.jar",
                "/home/terje/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar",
                "/home/terje/.ivy2/cache/com.google.guava/guava/bundles/guava-18.0.jar",
                "/home/terje/.ivy2/cache/commons-io/commons-io/jars/commons-io-2.4.jar",
                "/home/terje/.ivy2/cache/commons-net/commons-net/jars/commons-net-3.3.jar",
                "/home/terje/.ivy2/cache/org.apache.commons/commons-lang3/jars/commons-lang3-3.4.jar",
                "/home/terje/.ivy2/cache/org.apache.httpcomponents/httpclient/jars/httpclient-4.5.2.jar",
                "/home/terje/.ivy2/cache/org.apache.httpcomponents/httpcore/jars/httpcore-4.4.4.jar",
                "/home/terje/.ivy2/cache/org.apache.httpcomponents/httpmime/jars/httpmime-4.5.1.jar",
                "/home/terje/.ivy2/cache/org.springframework.boot/spring-boot-starter-redis/jars/spring-boot-starter-redis-1.2.6.RELEASE.jar",
                "/home/terje/.ivy2/cache/org.springframework.boot/spring-boot-starter-web/jars/spring-boot-starter-web-1.2.6.RELEASE.jar",
                "/home/terje/.ivy2/cache/org.springframework.session/spring-session/jars/spring-session-1.0.2.RELEASE.jar",
                "/home/terje/.ivy2/cache/com.github.kstyrc/embedded-redis/jars/embedded-redis-0.6.jar",
                "/home/terje/.ivy2/cache/com.github.jedis-lock/jedis-lock/jars/jedis-lock-1.0.0.jar"]

test-dependencies = ["/home/terje/.ivy2/cache/com.novocode/junit-interface/jars/junit-interface-0.11.jar",
                     "/home/terje/.ivy2/cache/org.easymock/easymock/jars/easymock-3.4.jar",
                     "/home/terje/.ivy2/cache/org.springframework/spring-test/jars/spring-test-4.1.0.RELEASE.jar",
                     "/home/terje/.ivy2/cache/org.hamcrest/hamcrest-junit/jars/hamcrest-junit-2.0.0.0.jar"]
```

I have tried the recent version and the problem still occurs. Do you have a sample project or something really eager to see how this works.

**Comment by mopemope** [comment]
@terlar OK. Please set `output` and `test-output`

```
# Set classes output directory
# Type: string
output = "build/main/classes"

# Set test classes output directory
# Type: string
test-output = "build/test/classes"
```

**Comment by terlar** [comment]
Thank you, it was not clear to me which configuration was required and what defaults worked out/existed. With this configuration it seems to be working smooth. Good to see the check that adds some new warnings.

Using `sbt` as build tool, this was my config if anyone else uses that:

```
output = "target/scala-2.10/classes"
test-output = "target/scala-2.10/test-classes"
```
