### ISSUE TITLE
NPE CommandHandler showDeclaration on dev

### ISSUE THREAD

**Issue by gerritjvv** [mopemope/meghanada-server#21]
Note: I've tested with the dev branch and copied the jar to 0.7.5.jar to make things easier  

```
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[meghanada-0.7.5.jar:?]
	at com.google.common.base.Joiner.toString(Joiner.java:454) ~[meghanada-0.7.5.jar:?]
	at com.google.common.base.Joiner.appendTo(Joiner.java:106) ~[meghanada-0.7.5.jar:?]
	at com.google.common.base.Joiner.appendTo(Joiner.java:154) ~[meghanada-0.7.5.jar:?]
	at com.google.common.base.Joiner.join(Joiner.java:197) ~[meghanada-0.7.5.jar:?]
	at com.google.common.base.Joiner.join(Joiner.java:187) ~[meghanada-0.7.5.jar:?]
	at meghanada.docs.declaration.DeclarationSearcher.lambda$searchMethodCall$8(DeclarationSearcher.java:141) ~[meghanada-0.7.5.jar:?]
	at meghanada.docs.declaration.DeclarationSearcher$$Lambda$289/1849122699.apply(Unknown Source) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51]
	at meghanada.docs.declaration.DeclarationSearcher.searchMethodCall(DeclarationSearcher.java:116) ~[meghanada-0.7.5.jar:?]
	at meghanada.docs.declaration.DeclarationSearcher$$Lambda$279/516879897.apply(Unknown Source) ~[?:?]
	at meghanada.docs.declaration.DeclarationSearcher.lambda$searchDeclaration$13(DeclarationSearcher.java:222) ~[meghanada-0.7.5.jar:?]
	at meghanada.docs.declaration.DeclarationSearcher$$Lambda$283/580245792.apply(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_51]
	at meghanada.docs.declaration.DeclarationSearcher.lambda$searchDeclaration$14(DeclarationSearcher.java:224) ~[meghanada-0.7.5.jar:?]
	at meghanada.docs.declaration.DeclarationSearcher$$Lambda$282/803597157.apply(Unknown Source) ~[?:?]
	at java.util.Optional.flatMap(Optional.java:241) ~[?:1.8.0_51]
	at meghanada.docs.declaration.DeclarationSearcher.searchDeclaration(DeclarationSearcher.java:221) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.Session.showDeclaration(Session.java:642) ~[meghanada-0.7.5.jar:?]
	at meghanada.server.CommandHandler.showDeclaration(CommandHandler.java:281) ~[meghanada-0.7.5.jar:?]
	... 14 more
[2017-05-16 00:48:30,161][INFO ][EmacsServer   : 148] lambda$acceptConnectio - client disconnect

```

**Comment by gerritjvv** [comment]
seems like MethodCall 's arguments field gets set in several places in TreeAnalyzer, probably a good idea to make access to arguments private and use a set method, that if null creates an empty ArrayList, wdyt?

**Comment by mopemope** [comment]
@gerritjvv Thank you for your report.
