### ISSUE TITLE
NPE JavaCompletion completionFieldsOrMethods in dev

### ISSUE THREAD

**Issue by gerritjvv** [mopemope/meghanada-server#23]
The fqcn from the variable is null here.

```               
 // get data from reflector
                String fqcn = variable.fqcn;
                if (!fqcn.contains(".")) {
                    fqcn = ownPackage + '.' + fqcn;
                }
```

```
[2017-05-16 09:56:56,150][ERROR][JavaCompletion: 425] completionAt           - Catching
java.lang.NullPointerException: null
	at meghanada.completion.JavaCompletion.completionFieldsOrMethods(JavaCompletion.java:335) ~[meghanada-0.7.5.jar:?]
	at meghanada.completion.JavaCompletion.specialCompletion(JavaCompletion.java:523) ~[meghanada-0.7.5.jar:?]
	at meghanada.completion.JavaCompletion.completionAt(JavaCompletion.java:417) [meghanada-0.7.5.jar:?]
	at meghanada.session.Session.completionAt(Session.java:355) [meghanada-0.7.5.jar:?]
	at meghanada.server.CommandHandler.autocomplete(CommandHandler.java:95) [meghanada-0.7.5.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$5(EmacsServer.java:172) [meghanada-0.7.5.jar:?]
	at meghanada.server.emacs.EmacsServer$$Lambda$221/1808075716.apply(Unknown Source) [meghanada-0.7.5.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) [meghanada-0.7.5.jar:?]
	at com.leacox.motif.matching.Matching1$$Lambda$219/86750035.apply(Unknown Source) [meghanada-0.7.5.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) [meghanada-0.7.5.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) [meghanada-0.7.5.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:280) [meghanada-0.7.5.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$2(EmacsServer.java:128) [meghanada-0.7.5.jar:?]
	at meghanada.server.emacs.EmacsServer$$Lambda$39/812553708.run(Unknown Source) [meghanada-0.7.5.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

**Comment by mopemope** [comment]
@gerritjvv Thanks. But I couldn't reproduce it.
Please would you tell me more details ?

**Comment by gerritjvv** [comment]
both the NPE errors I've reported happen when I'm trying method completion for argument in lambda statements, sometimes nested.
