### ISSUE TITLE
NullPointerException during call to showDeclaration

### ISSUE THREAD

**Issue by terlar** [mopemope/meghanada-server#25]
I got another NullPointer exception during my random browsing through my code, not sure at what point `showDeclaration` is triggered, but here is my stack trace:

```
[2017-05-17 16:13:06,396][ERROR][CommandHandler: 292] showDeclaration        - Catching
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[meghanada-0.7.6.jar:?]
	at com.google.common.base.Joiner.toString(Joiner.java:454) ~[meghanada-0.7.6.jar:?]
	at com.google.common.base.Joiner.appendTo(Joiner.java:106) ~[meghanada-0.7.6.jar:?]
	at com.google.common.base.Joiner.appendTo(Joiner.java:154) ~[meghanada-0.7.6.jar:?]
	at com.google.common.base.Joiner.join(Joiner.java:197) ~[meghanada-0.7.6.jar:?]
	at com.google.common.base.Joiner.join(Joiner.java:187) ~[meghanada-0.7.6.jar:?]
	at meghanada.docs.declaration.DeclarationSearcher.lambda$searchMethodCall$8(DeclarationSearcher.java:166) ~[meghanada-0.7.6.jar:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_121]
	at meghanada.docs.declaration.DeclarationSearcher.searchMethodCall(DeclarationSearcher.java:131) ~[meghanada-0.7.6.jar:?]
	at meghanada.docs.declaration.DeclarationSearcher.lambda$null$13(DeclarationSearcher.java:258) ~[meghanada-0.7.6.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_121]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_121]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_121]
	at meghanada.docs.declaration.DeclarationSearcher.lambda$searchDeclaration$14(DeclarationSearcher.java:260) ~[meghanada-0.7.6.jar:?]
	at java.util.Optional.flatMap(Optional.java:241) ~[?:1.8.0_121]
	at meghanada.docs.declaration.DeclarationSearcher.searchDeclaration(DeclarationSearcher.java:254) ~[meghanada-0.7.6.jar:?]
	at meghanada.session.Session.showDeclaration(Session.java:668) ~[meghanada-0.7.6.jar:?]
	at meghanada.server.CommandHandler.showDeclaration(CommandHandler.java:285) ~[meghanada-0.7.6.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$14(EmacsServer.java:184) ~[meghanada-0.7.6.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-0.7.6.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-0.7.6.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-0.7.6.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:226) ~[meghanada-0.7.6.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$22(EmacsServer.java:306) ~[meghanada-0.7.6.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[2017-05-17 16:13:06,413][ERROR][EmacsServer   : 319] lambda$acceptConnectio - Catching
meghanada.server.CommandException: java.lang.NullPointerException
	at meghanada.server.CommandHandler.showDeclaration(CommandHandler.java:293) ~[meghanada-0.7.6.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$14(EmacsServer.java:184) ~[meghanada-0.7.6.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-0.7.6.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-0.7.6.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-0.7.6.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:226) ~[meghanada-0.7.6.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$22(EmacsServer.java:306) ~[meghanada-0.7.6.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[meghanada-0.7.6.jar:?]
	at com.google.common.base.Joiner.toString(Joiner.java:454) ~[meghanada-0.7.6.jar:?]
	at com.google.common.base.Joiner.appendTo(Joiner.java:106) ~[meghanada-0.7.6.jar:?]
	at com.google.common.base.Joiner.appendTo(Joiner.java:154) ~[meghanada-0.7.6.jar:?]
	at com.google.common.base.Joiner.join(Joiner.java:197) ~[meghanada-0.7.6.jar:?]
	at com.google.common.base.Joiner.join(Joiner.java:187) ~[meghanada-0.7.6.jar:?]
	at meghanada.docs.declaration.DeclarationSearcher.lambda$searchMethodCall$8(DeclarationSearcher.java:166) ~[meghanada-0.7.6.jar:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_121]
	at meghanada.docs.declaration.DeclarationSearcher.searchMethodCall(DeclarationSearcher.java:131) ~[meghanada-0.7.6.jar:?]
	at meghanada.docs.declaration.DeclarationSearcher.lambda$null$13(DeclarationSearcher.java:258) ~[meghanada-0.7.6.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_121]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_121]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_121]
	at meghanada.docs.declaration.DeclarationSearcher.lambda$searchDeclaration$14(DeclarationSearcher.java:260) ~[meghanada-0.7.6.jar:?]
	at java.util.Optional.flatMap(Optional.java:241) ~[?:1.8.0_121]
	at meghanada.docs.declaration.DeclarationSearcher.searchDeclaration(DeclarationSearcher.java:254) ~[meghanada-0.7.6.jar:?]
	at meghanada.session.Session.showDeclaration(Session.java:668) ~[meghanada-0.7.6.jar:?]
	at meghanada.server.CommandHandler.showDeclaration(CommandHandler.java:285) ~[meghanada-0.7.6.jar:?]
	... 11 more
[2017-05-17 16:13:06,420][INFO ][EmacsServer   : 326] lambda$acceptConnectio - client disconnect
```

**Comment by mopemope** [comment]
@terlar Why does not your code get AssertionError?

**Comment by terlar** [comment]
I am not sure, the interface kind of freezes for a while and then I pressed `Ctrl+g` and then it crashed/disconnected. Any way I can debug this?

**Comment by mopemope** [comment]
It is elisp's problem.please check version 0.7.7.
