### ISSUE TITLE
ParseProblemException when trying to jump to a declaration.

### ISSUE THREAD

**Issue by zbelial** [mopemope/meghanada-server#26]
When I try to jump to the declaration of a private member of a class, meghanada server reports an exception, and the client loses the connection to the server.

Following is the stacktrace:
<code>
[2017-05-18 12:45:19,562][ERROR][CommandHandler: 203] jumpDeclaration        - Catching
com.github.javaparser.ParseProblemException: (line 25,col 92) Parse error. Found "null", expected one of  "!=" "%" "%=" "&" "&&" "&=" ")" "*" "*=" "+" "+=" "," "-" "-=" "->" "/" "/=" "::" "<" "<<=" "<=" "=" "==" ">" ">=" ">>=" ">>>=" "?" "^" "^=" "instanceof" "|" "|=" "||"
Problem stacktrace : 
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:9873)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:9729)
  com.github.javaparser.GeneratedJavaParser.Arguments(GeneratedJavaParser.java:3440)
  com.github.javaparser.GeneratedJavaParser.AllocationExpression(GeneratedJavaParser.java:3521)
  com.github.javaparser.GeneratedJavaParser.PrimaryPrefix(GeneratedJavaParser.java:3145)
  com.github.javaparser.GeneratedJavaParser.PrimaryExpression(GeneratedJavaParser.java:2862)
  com.github.javaparser.GeneratedJavaParser.PostfixExpression(GeneratedJavaParser.java:2766)
  com.github.javaparser.GeneratedJavaParser.UnaryExpressionNotPlusMinus(GeneratedJavaParser.java:2751)
  com.github.javaparser.GeneratedJavaParser.UnaryExpression(GeneratedJavaParser.java:2658)
  com.github.javaparser.GeneratedJavaParser.MultiplicativeExpression(GeneratedJavaParser.java:2549)
  com.github.javaparser.GeneratedJavaParser.AdditiveExpression(GeneratedJavaParser.java:2511)
  com.github.javaparser.GeneratedJavaParser.ShiftExpression(GeneratedJavaParser.java:2475)
  com.github.javaparser.GeneratedJavaParser.RelationalExpression(GeneratedJavaParser.java:2425)
  com.github.javaparser.GeneratedJavaParser.InstanceOfExpression(GeneratedJavaParser.java:2405)
  com.github.javaparser.GeneratedJavaParser.EqualityExpression(GeneratedJavaParser.java:2367)
  com.github.javaparser.GeneratedJavaParser.AndExpression(GeneratedJavaParser.java:2345)
  com.github.javaparser.GeneratedJavaParser.ExclusiveOrExpression(GeneratedJavaParser.java:2324)
  com.github.javaparser.GeneratedJavaParser.InclusiveOrExpression(GeneratedJavaParser.java:2303)
  com.github.javaparser.GeneratedJavaParser.ConditionalAndExpression(GeneratedJavaParser.java:2282)
  com.github.javaparser.GeneratedJavaParser.ConditionalOrExpression(GeneratedJavaParser.java:2261)
  com.github.javaparser.GeneratedJavaParser.ConditionalExpression(GeneratedJavaParser.java:2242)
  com.github.javaparser.GeneratedJavaParser.Expression(GeneratedJavaParser.java:2075)
  com.github.javaparser.GeneratedJavaParser.VariableInitializer(GeneratedJavaParser.java:1019)
  com.github.javaparser.GeneratedJavaParser.VariableDeclarator(GeneratedJavaParser.java:940)
  com.github.javaparser.GeneratedJavaParser.FieldDeclaration(GeneratedJavaParser.java:912)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBodyDeclaration(GeneratedJavaParser.java:856)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBody(GeneratedJavaParser.java:783)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceDeclaration(GeneratedJavaParser.java:436)
  com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:195)
  com.github.javaparser.JavaParser.parse(JavaParser.java:125)
  com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:393)
  com.github.javaparser.JavaParser.parse(JavaParser.java:252)
  meghanada.location.LocationSearcher.searchLocationFromFile(LocationSearcher.java:87)
  meghanada.location.LocationSearcher.searchLocationFromDecompileFile(LocationSearcher.java:636)
  meghanada.location.LocationSearcher.lambda$getLocationFromSrcOrDecompile$22(LocationSearcher.java:577)
  meghanada.utils.FunctionUtils.lambda$wrapIO$1(FunctionUtils.java:24)
  java.util.Optional.orElseGet(Optional.java:267)
  meghanada.location.LocationSearcher.getLocationFromSrcOrDecompile(LocationSearcher.java:576)
  meghanada.location.LocationSearcher.searchFromDependency(LocationSearcher.java:551)
  meghanada.location.LocationSearcher.lambda$null$18(LocationSearcher.java:479)
  meghanada.utils.FunctionUtils.lambda$wrapIO$1(FunctionUtils.java:24)
  java.util.Optional.orElseGet(Optional.java:267)
  meghanada.location.LocationSearcher.lambda$getFQCNLocation$19(LocationSearcher.java:479)
  meghanada.utils.FunctionUtils.lambda$wrapIO$1(FunctionUtils.java:24)
  java.util.Optional.orElseGet(Optional.java:267)
  meghanada.location.LocationSearcher.getFQCNLocation(LocationSearcher.java:474)
  meghanada.location.LocationSearcher.lambda$searchLocalVariable$1(LocationSearcher.java:277)
  java.util.Optional.map(Optional.java:215)
  meghanada.location.LocationSearcher.searchLocalVariable(LocationSearcher.java:266)
  meghanada.location.LocationSearcher.lambda$searchDeclarationLocation$4(LocationSearcher.java:313)
  java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
  java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
  java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
  java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
  java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
  java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
  java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
  java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
  meghanada.location.LocationSearcher.searchDeclarationLocation(LocationSearcher.java:315)
  meghanada.session.Session.jumpDeclaration(Session.java:605)
  meghanada.server.CommandHandler.jumpDeclaration(CommandHandler.java:197)
  meghanada.server.emacs.EmacsServer.lambda$dispatch$13(EmacsServer.java:176)
  com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45)
  com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40)
  com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118)
  meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:226)
  meghanada.server.emacs.EmacsServer.lambda$acceptConnection$22(EmacsServer.java:306)
  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)

	at com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:397) ~[meghanada-0.7.6.jar:?]
	at com.github.javaparser.JavaParser.parse(JavaParser.java:252) ~[meghanada-0.7.6.jar:?]
	at meghanada.location.LocationSearcher.searchLocationFromFile(LocationSearcher.java:87) ~[meghanada-0.7.6.jar:?]
	at meghanada.location.LocationSearcher.searchLocationFromDecompileFile(LocationSearcher.java:636) ~[meghanada-0.7.6.jar:?]
	at meghanada.location.LocationSearcher.lambda$getLocationFromSrcOrDecompile$22(LocationSearcher.java:577) ~[meghanada-0.7.6.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIO$1(FunctionUtils.java:24) ~[meghanada-0.7.6.jar:?]
	at java.util.Optional.orElseGet(Optional.java:267) ~[?:1.8.0_121]
	at meghanada.location.LocationSearcher.getLocationFromSrcOrDecompile(LocationSearcher.java:576) ~[meghanada-0.7.6.jar:?]
	at meghanada.location.LocationSearcher.searchFromDependency(LocationSearcher.java:551) ~[meghanada-0.7.6.jar:?]
	at meghanada.location.LocationSearcher.lambda$null$18(LocationSearcher.java:479) ~[meghanada-0.7.6.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIO$1(FunctionUtils.java:24) ~[meghanada-0.7.6.jar:?]
	at java.util.Optional.orElseGet(Optional.java:267) ~[?:1.8.0_121]
	at meghanada.location.LocationSearcher.lambda$getFQCNLocation$19(LocationSearcher.java:479) ~[meghanada-0.7.6.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIO$1(FunctionUtils.java:24) ~[meghanada-0.7.6.jar:?]
	at java.util.Optional.orElseGet(Optional.java:267) ~[?:1.8.0_121]
	at meghanada.location.LocationSearcher.getFQCNLocation(LocationSearcher.java:474) ~[meghanada-0.7.6.jar:?]
	at meghanada.location.LocationSearcher.lambda$searchLocalVariable$1(LocationSearcher.java:277) ~[meghanada-0.7.6.jar:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_121]
	at meghanada.location.LocationSearcher.searchLocalVariable(LocationSearcher.java:266) ~[meghanada-0.7.6.jar:?]
	at meghanada.location.LocationSearcher.lambda$searchDeclarationLocation$4(LocationSearcher.java:313) ~[meghanada-0.7.6.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_121]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_121]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_121]
	at meghanada.location.LocationSearcher.searchDeclarationLocation(LocationSearcher.java:315) ~[meghanada-0.7.6.jar:?]
	at meghanada.session.Session.jumpDeclaration(Session.java:605) ~[meghanada-0.7.6.jar:?]
	at meghanada.server.CommandHandler.jumpDeclaration(CommandHandler.java:197) ~[meghanada-0.7.6.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$13(EmacsServer.java:176) ~[meghanada-0.7.6.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-0.7.6.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-0.7.6.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-0.7.6.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:226) ~[meghanada-0.7.6.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$22(EmacsServer.java:306) ~[meghanada-0.7.6.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
<code>

**Comment by zbelial** [comment]
Here is the class that caused the problem, and what I wanted to do is jumping to the declaration of cardFileDir from its usage in getCardFileDir().

```java

package com.heping.cmserver.pojo;

/**
 * Describe class CMServerConfigBean here.
 *
 *
 * Created: Sun Jan 22 20:37:27 2017
 *
 * @author <a href="mailto:jiyang.zhao@dingdingtingche.com.cn">zbelial</a>
 * @version 1.0
 */


public class CMServerConfigBean {
    private String cardFileDir;

    /**
     * Creates a new CMServerConfigBean instance.
     *
     */
    public CMServerConfigBean() {

    }

    public final String getCardFileDir() {
        return cardFileDir;
    }

    public final void setCardFileDir(final String cardFileDir) {
        this.cardFileDir = cardFileDir;
    }

}

```

**Comment by mopemope** [comment]
@zbelial Thank you for your report. Please check latest verion.
