### ISSUE TITLE
NoSuchElementException when opening a java file.

### ISSUE THREAD

**Issue by zbelial** [mopemope/meghanada-server#28]
Meghanada reported the following error when I opened a java file. I'm using meghanada 0.7.10 and openjdk 1.8.0.

[2017-05-27 17:46:41,873][INFO ][CacheEventSubs:  52] analyze                - start analyze sources ...
[2017-05-27 17:46:47,684][ERROR][Project       : 294] compileJava            - Catching
java.util.NoSuchElementException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598) ~[?:1.8.0_131]
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677) ~[?:1.8.0_131]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735) ~[?:1.8.0_131]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) ~[?:1.8.0_131]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) ~[?:1.8.0_131]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:1.8.0_131]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_131]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583) ~[?:1.8.0_131]
	at meghanada.analyze.TreeAnalyzer.analyze(TreeAnalyzer.java:1943) ~[meghanada-0.7.10.jar:?]
	at meghanada.analyze.JavaAnalyzer.runAnalyzeAndCompile(JavaAnalyzer.java:163) ~[meghanada-0.7.10.jar:?]
	at meghanada.analyze.JavaAnalyzer.analyzeAndCompile(JavaAnalyzer.java:105) ~[meghanada-0.7.10.jar:?]
	at meghanada.project.Project.compileJava(Project.java:279) ~[meghanada-0.7.10.jar:?]
	at meghanada.project.gradle.GradleProject.compileJava(GradleProject.java:421) ~[meghanada-0.7.10.jar:?]
	at meghanada.project.gradle.GradleProject.compileJava(GradleProject.java:411) ~[meghanada-0.7.10.jar:?]
	at meghanada.session.subscribe.CacheEventSubscriber.lambda$analyze$1(CacheEventSubscriber.java:57) ~[meghanada-0.7.10.jar:?]
	at meghanada.config.Config.timeItF(Config.java:111) [meghanada-0.7.10.jar:?]
	at meghanada.session.subscribe.CacheEventSubscriber.analyze(CacheEventSubscriber.java:53) [meghanada-0.7.10.jar:?]
	at meghanada.session.subscribe.CacheEventSubscriber.on(CacheEventSubscriber.java:33) [meghanada-0.7.10.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [meghanada-0.7.10.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [meghanada-0.7.10.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [meghanada-0.7.10.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_131]
	at meghanada.analyze.TreeAnalyzer.analyzeIdent(TreeAnalyzer.java:1714) ~[meghanada-0.7.10.jar:?]
	at meghanada.analyze.TreeAnalyzer.analyzeParsedTree(TreeAnalyzer.java:568) ~[meghanada-0.7.10.jar:?]
	at meghanada.analyze.TreeAnalyzer.analyzeFieldAccess(TreeAnalyzer.java:1467) ~[meghanada-0.7.10.jar:?]
	at meghanada.analyze.TreeAnalyzer.analyzeParsedTree(TreeAnalyzer.java:543) ~[meghanada-0.7.10.jar:?]
	at meghanada.analyze.TreeAnalyzer.analyzeFieldAccess(TreeAnalyzer.java:1467) ~[meghanada-0.7.10.jar:?]
	at meghanada.analyze.TreeAnalyzer.analyzeParsedTree(TreeAnalyzer.java:543) ~[meghanada-0.7.10.jar:?]
	at meghanada.analyze.TreeAnalyzer.analyzeCompilationUnitTree(TreeAnalyzer.java:438) ~[meghanada-0.7.10.jar:?]
	at meghanada.analyze.TreeAnalyzer.analyzeUnit(TreeAnalyzer.java:1980) ~[meghanada-0.7.10.jar:?]
	at meghanada.analyze.TreeAnalyzer.lambda$analyze$40(TreeAnalyzer.java:1946) ~[meghanada-0.7.10.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIOConsumer$2(FunctionUtils.java:34) ~[meghanada-0.7.10.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_131]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_131]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_131]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[?:1.8.0_131]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_131]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_131]
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040) ~[?:1.8.0_131]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058) ~[?:1.8.0_131]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_131]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_131]
[2017-05-27 17:46:47,796][WARN ][CacheEventSubs:  71] lambda$analyze$1       - Compile Error : null
[2017-05-27 17:46:47,796][INFO ][Config        : 115] timeItF                - analyzed and compiled. elapsed:5.922 s

**Comment by mopemope** [comment]
@zbelial I couldn't reproduce it. Please check your java home.

**Comment by zbelial** [comment]
Sorry. This was my fault. There were some invalid settings in my build.gradle.  After correcting these errors, the exception disappears.
