### ISSUE TITLE
IndexOutOfBoundsException when starting server

### ISSUE THREAD

**Issue by mnuessler** [mopemope/meghanada-server#36]
When trying to use Meghanada on a Maven project, starting the server fails with an `IndexOutOfBoundsException`:

```
[2017-10-05 10:11:21,740][INFO ][Main          : 125] main                   - Meghanada-Server Version:0.8.3-507f400
[2017-10-05 10:11:22,406][ERROR][EmacsServer   : 311] startServer            - Catching
java.lang.ExceptionInInitializerError: null
	at jetbrains.exodus.env.StoreImpl.<init>(StoreImpl.java:53) ~[meghanada-0.8.3.jar:?]
	at jetbrains.exodus.env.EnvironmentImpl.createStore(EnvironmentImpl.java:469) ~[meghanada-0.8.3.jar:?]
	at jetbrains.exodus.env.EnvironmentImpl.openStoreImpl(EnvironmentImpl.java:672) ~[meghanada-0.8.3.jar:?]
	at jetbrains.exodus.env.EnvironmentImpl.openStore(EnvironmentImpl.java:162) ~[meghanada-0.8.3.jar:?]
	at jetbrains.exodus.env.EnvironmentImpl.openStore(EnvironmentImpl.java:45) ~[meghanada-0.8.3.jar:?]
	at jetbrains.exodus.entitystore.PersistentEntityStoreImpl$2.compute(PersistentEntityStoreImpl.java:205) ~[meghanada-0.8.3.jar:?]
	at jetbrains.exodus.entitystore.PersistentEntityStoreImpl$2.compute(PersistentEntityStoreImpl.java:201) ~[meghanada-0.8.3.jar:?]
	at jetbrains.exodus.entitystore.PersistentEntityStoreImpl.computeInTransaction(PersistentEntityStoreImpl.java:576) ~[meghanada-0.8.3.jar:?]
	at jetbrains.exodus.entitystore.PersistentEntityStoreImpl.init(PersistentEntityStoreImpl.java:201) ~[meghanada-0.8.3.jar:?]
	at jetbrains.exodus.entitystore.PersistentEntityStoreImpl.<init>(PersistentEntityStoreImpl.java:181) ~[meghanada-0.8.3.jar:?]
	at jetbrains.exodus.entitystore.PersistentEntityStores.newInstance(PersistentEntityStores.java:41) ~[meghanada-0.8.3.jar:?]
	at jetbrains.exodus.entitystore.PersistentEntityStores.newInstance(PersistentEntityStores.java:47) ~[meghanada-0.8.3.jar:?]
	at jetbrains.exodus.entitystore.PersistentEntityStores.newInstance(PersistentEntityStores.java:57) ~[meghanada-0.8.3.jar:?]
	at meghanada.store.ProjectDatabase.open(ProjectDatabase.java:341) ~[meghanada-0.8.3.jar:?]
	at meghanada.store.ProjectDatabase.<init>(ProjectDatabase.java:74) ~[meghanada-0.8.3.jar:?]
	at meghanada.store.ProjectDatabase.getInstance(ProjectDatabase.java:96) ~[meghanada-0.8.3.jar:?]
	at meghanada.store.ProjectDatabaseHelper.loadProject(ProjectDatabaseHelper.java:205) ~[meghanada-0.8.3.jar:?]
	at meghanada.project.Project.loadProject(Project.java:129) ~[meghanada-0.8.3.jar:?]
	at meghanada.session.Session.loadProject(Session.java:160) ~[meghanada-0.8.3.jar:?]
	at meghanada.session.Session.findProject(Session.java:121) ~[meghanada-0.8.3.jar:?]
	at meghanada.session.Session.createSession(Session.java:97) ~[meghanada-0.8.3.jar:?]
	at meghanada.session.Session.createSession(Session.java:92) ~[meghanada-0.8.3.jar:?]
	at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:306) [meghanada-0.8.3.jar:?]
	at meghanada.Main.main(Main.java:127) [meghanada-0.8.3.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Indexed access out of bounds: 1, 1
	at java.util.Objects.outOfBounds(Objects.java:365) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:436) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:388) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:435) ~[?:?]
	at jetbrains.exodus.util.StringInterner.<clinit>(StringInterner.kt:55) ~[meghanada-0.8.3.jar:?]
	... 24 more
[2017-10-05 10:11:22,419][INFO ][Main          :  69] lambda$main$0          - shutdown server
```

**Comment by zovt** [comment]
Same issue. Temporarily fixed by downloading the 0.7.9 release [https://dl.bintray.com/mopemope/meghanada/] and renaming it to meghanada-0.8.3.jar in the .emacs.d/meghanada directory

**Comment by s-kostyaev** [comment]
I have same issue on Ubuntu 17.04 but all works fine on archlinux. Maybe incompatible version of some components. I hope it can help to find cause of the problem.

**Comment by s-kostyaev** [comment]
In ubuntu I fix it by change java version to java 8:
```
sudo update-alternatives --config java
```

**Comment by s-kostyaev** [comment]
Looks like `meghanada-server` incompatile with java 9.
