### ISSUE TITLE
BindException at server start

### ISSUE THREAD

**Issue by dim3nsi4** [mopemope/meghanada-server#38]
Hi,

Sometimes, the Meghanada  server fails to start and throws the following exception:

> Exception in thread "main" java.net.BindException: Address already in use (Bind failed)
> at java.net.PlainSocketImpl.socketBind(Native Method)
> at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
> at java.net.ServerSocket.bind(ServerSocket.java:375)
> at java.net.ServerSocket.<init>(ServerSocket.java:237)
> at meghanada.server.emacs.EmacsServer.<init>(EmacsServer.java:56)
> at meghanada.Main.createServer(Main.java:153)
> at meghanada.Main.main(Main.java:126)

This happens for example when 2 java projects are opened in their own emacs session. On a server, it can even happen when there is only a single Java project opened.

Regards

**Comment by dim3nsi4** [comment]
So I've looked a bit at the sources and it seems it is a bit problematic to fix (at least with my current understanding). The port is fixed on both the server side and on emacs side (`meghanada.el`). Modifying the server seems immediate: in the class `EmacsServer`, I would replace the current assignment of the port in the constructor
> this.port = port;

with 

> this.port = this.serverSocket.getLocalPort();

That way, if the server received a port equal to 0, it will choose the port automatically. The default port in the class `Main` could also be changed to 0.

A fixed port on emacs side seems however to be necessary in order to know which port to use to communicate with the server. Ideally, emacs would start the server without indicating a specific port and the server would return to emacs the port it is currently using. Unfortunately, I have currently no idea on how to accomplish this. Any input is welcome ! :)
