### ISSUE TITLE
Null pointer exception everywhere

### ISSUE THREAD

**Issue by MAliNaqvi** [mopemope/meghanada-server#40]
Hi folks,
I have tried the server on both macos and windows 10. I seem to get this same error. 

I tried the server on a maven and gradle project, neither seem to be working. 

I am using it with spacemacs. 

![meghanada-server_error](https://user-images.githubusercontent.com/13531332/32457631-c5de738a-c2f7-11e7-9c6c-32946b9a1114.png)

**Comment by mopemope** [comment]
@MAliNaqvi see https://github.com/mopemope/meghanada-emacs/issues/30

**Comment by MAliNaqvi** [comment]
I have tried with both JDK 7 and 8. Right now I have set JAVA_HOME to jdk 8.

The server starts correctly and says that it is connected.


On 7 Nov 2017 08:06, Yutaka Matsubara <notifications@github.com> wrote:

@MAliNaqvi<https://github.com/malinaqvi> see mopemope/meghanada-emacs#30<https://github.com/mopemope/meghanada-emacs/issues/30>

**Comment by MAliNaqvi** [comment]
@mopemope 

It seems like this happens even without emacs:

```
C:\Users\alnaqvi\project\meghanada-server\build\libs>java -jar meghanada-0.8.3.jar
[2017-11-08 11:26:55,604][INFO ][Main          : 125] main                   - Meghanada-Server Version:0.8.3-507f400
[2017-11-08 11:26:56,148][INFO ][Session       : 164] loadProject            - load project from cache. projectRoot:C:\Users\alnaca\ideproject\meghanada-server
[2017-11-08 11:26:56,205][INFO ][EmacsServer   : 308] startServer            - Start server Listen localhost:55555
[2017-11-08 11:26:56,637][INFO ][Config        : 115] timeItF                - create class index ... read 146 jars. elapsed:429.0 ms
[2017-11-08 11:26:56,640][INFO ][CacheEventSubs:  66] analyze                - start analyze sources ...
[2017-11-08 11:26:56,704][ERROR][Project       : 310] compileJava            - Catching
java.lang.NullPointerException: null
        at meghanada.analyze.JavaAnalyzer.runAnalyzeAndCompile(JavaAnalyzer.java:140) ~[meghanada-0.8.3.jar:?]
        at meghanada.analyze.JavaAnalyzer.analyzeAndCompile(JavaAnalyzer.java:126) ~[meghanada-0.8.3.jar:?]
        at meghanada.project.Project.compileJava(Project.java:295) ~[meghanada-0.8.3.jar:?]
        at meghanada.project.gradle.GradleProject.compileJava(GradleProject.java:473) ~[meghanada-0.8.3.jar:?]
        at meghanada.project.gradle.GradleProject.compileJava(GradleProject.java:463) ~[meghanada-0.8.3.jar:?]
        at meghanada.session.subscribe.CacheEventSubscriber.lambda$analyze$3(CacheEventSubscriber.java:71) ~[meghanada-0.8.3.jar:?]
        at meghanada.config.Config.timeItF(Config.java:111) [meghanada-0.8.3.jar:?]
        at meghanada.session.subscribe.CacheEventSubscriber.analyze(CacheEventSubscriber.java:67) [meghanada-0.8.3.jar:?]
        at meghanada.session.subscribe.CacheEventSubscriber.on(CacheEventSubscriber.java:31) [meghanada-0.8.3.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_152]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [meghanada-0.8.3.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [meghanada-0.8.3.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [meghanada-0.8.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_152]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_152]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]
[2017-11-08 11:26:56,716][WARN ][CacheEventSubs:  85] lambda$analyze$3       - compile message  null
```

this is after compiling via `gradlew clean shadowJar`
