### ISSUE TITLE
IllegalArgumentException when parsing project

### ISSUE THREAD

**Issue by dakrone** [mopemope/meghanada-server#43]
When I try to load up my project with megahanada, I get the following stacktrace from the server:

```
[2017-11-27 14:15:01,987][INFO ][Main          : 125] main                   - Meghanada-Server Version:0.8.3-507f400
[2017-11-27 14:15:03,639][INFO ][GradleProject : 139] parseProject           - loading gradle project:/home/hinmanm/es/elasticsearch/core/build.gradle
Downloading https://services.gradle.org/distributions/gradle-4.0.1-bin.zip
................................................................
Unzipping /home/hinmanm/.gradle/wrapper/dists/gradle-4.0.1-bin/82ajq2mkcvzmyzskx3tahg8op/gradle-4.0.1-bin.zip to /home/hinmanm/.gradle/wrapper/dists/gradle-4.0.1-bin/82ajq2mkcvzmyzskx3tahg8op
Set executable permissions for: /home/hinmanm/.gradle/wrapper/dists/gradle-4.0.1-bin/82ajq2mkcvzmyzskx3tahg8op/gradle-4.0.1/bin/gradle
[2017-11-27 14:17:17,655][INFO ][Session       : 192] loadProject            - loaded project:/home/hinmanm/es/elasticsearch/core elapsed:2.234 min
[2017-11-27 14:17:17,853][INFO ][EmacsServer   : 308] startServer            - Start server Listen localhost:55555
[2017-11-27 14:17:17,860][INFO ][EmacsServer   : 329] accept                 - client connected
[2017-11-27 14:17:17,924][INFO ][GradleProject : 139] parseProject           - loading gradle project:/home/hinmanm/es/elasticsearch/core/cli/build.gradle
[2017-11-27 14:17:25,435][INFO ][Session       : 192] loadProject            - loaded project:/home/hinmanm/es/elasticsearch/core/cli elapsed:7.512 s
[2017-11-27 14:17:25,436][INFO ][ProjectDepende: 157] lambda$getProjectOutpu - skip build project core-cli
[2017-11-27 14:17:25,438][INFO ][ProjectDepende: 157] lambda$getProjectOutpu - skip build project core-cli
[2017-11-27 14:17:25,498][INFO ][GradleProject : 139] parseProject           - loading gradle project:/home/hinmanm/es/elasticsearch/client/rest/build.gradle
[2017-11-27 14:17:35,450][INFO ][Session       : 192] loadProject            - loaded project:/home/hinmanm/es/elasticsearch/client/rest elapsed:9.952 s
[2017-11-27 14:17:35,451][INFO ][ProjectDepende: 157] lambda$getProjectOutpu - skip build project client-rest
[2017-11-27 14:17:35,736][INFO ][GradleProject : 139] parseProject           - loading gradle project:/home/hinmanm/es/elasticsearch/test/framework/build.gradle
[2017-11-27 14:17:41,215][INFO ][Session       : 192] loadProject            - loaded project:/home/hinmanm/es/elasticsearch/test/framework elapsed:5.480 s
[2017-11-27 14:17:41,224][INFO ][ProjectDepende: 157] lambda$getProjectOutpu - skip build project test-framework
[2017-11-27 14:17:41,232][INFO ][ProjectDepende: 157] lambda$getProjectOutpu - skip build project core-cli
[2017-11-27 14:17:41,753][INFO ][Config        : 115] timeItF                - create class index ... read 79 jars. elapsed:517.0 ms
[2017-11-27 14:17:41,766][ERROR][Session       :  34] lambda$new$0           - java.lang.IllegalArgumentException
java.lang.RuntimeException: java.lang.IllegalArgumentException
	at meghanada.config.Config.timeItF(Config.java:113) ~[meghanada-0.8.3.jar:?]
	at meghanada.session.subscribe.CacheEventSubscriber.analyze(CacheEventSubscriber.java:55) ~[meghanada-0.8.3.jar:?]
	at meghanada.session.subscribe.CacheEventSubscriber.on(CacheEventSubscriber.java:31) ~[meghanada-0.8.3.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[meghanada-0.8.3.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[meghanada-0.8.3.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [meghanada-0.8.3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[meghanada-0.8.3.jar:?]
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[meghanada-0.8.3.jar:?]
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[meghanada-0.8.3.jar:?]
	at meghanada.reflect.asm.ASMReflector.readClassIndex(ASMReflector.java:146) ~[meghanada-0.8.3.jar:?]
	at meghanada.reflect.asm.ASMReflector.lambda$getClasses$4(ASMReflector.java:310) ~[meghanada-0.8.3.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIOConsumer$2(FunctionUtils.java:34) ~[meghanada-0.8.3.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_111]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_111]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[?:1.8.0_111]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:405) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) ~[?:1.8.0_111]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) ~[?:1.8.0_111]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:1.8.0_111]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_111]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583) ~[?:1.8.0_111]
	at meghanada.reflect.asm.ASMReflector.getClasses(ASMReflector.java:297) ~[meghanada-0.8.3.jar:?]
	at meghanada.reflect.asm.CachedASMReflector.lambda$createClassIndexes$1(CachedASMReflector.java:150) ~[meghanada-0.8.3.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIOConsumer$2(FunctionUtils.java:34) ~[meghanada-0.8.3.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_111]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_111]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[?:1.8.0_111]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:405) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) ~[?:1.8.0_111]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) ~[?:1.8.0_111]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:1.8.0_111]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_111]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583) ~[?:1.8.0_111]
	at meghanada.reflect.asm.CachedASMReflector.createClassIndexes(CachedASMReflector.java:132) ~[meghanada-0.8.3.jar:?]
	at meghanada.session.subscribe.CacheEventSubscriber.lambda$analyze$2(CacheEventSubscriber.java:59) ~[meghanada-0.8.3.jar:?]
	at meghanada.config.Config.timeItF(Config.java:111) ~[meghanada-0.8.3.jar:?]
	... 12 more
```

Sorry it's not much to go on, the only thing I've done was `meghanada-client-connect`

**Comment by mopemope** [comment]
I think that is probably due to the old version of ASM. It will probably be fixed in next version.
