### ISSUE TITLE
meghanada-run-junit-test-case results in: java.lang.NoSuchMethodError: org.apache.logging.log4j.Logger.debug(Ljava/lang/String;Ljava/lang/Object;)V

### ISSUE THREAD

**Issue by iocanel** [mopemope/meghanada-server#47]
14:46:07.867 [main] DEBUG meghanada.reflect.asm.CachedASMReflector - start createClassIndexes
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.logging.log4j.Logger.debug(Ljava/lang/String;Ljava/lang/Object;)V
	at meghanada.config.Config.<init>(Config.java:61)
	at meghanada.config.Config.load(Config.java:77)
	at meghanada.reflect.asm.ASMReflector.<init>(ASMReflector.java:63)
	at meghanada.reflect.asm.ASMReflector.getInstance(ASMReflector.java:68)
	at meghanada.reflect.asm.CachedASMReflector.lambda$createClassIndexes$1(CachedASMReflector.java:149)
	at meghanada.utils.FunctionUtils.lambda$wrapIOConsumer$2(FunctionUtils.java:34)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at meghanada.reflect.asm.CachedASMReflector.createClassIndexes(CachedASMReflector.java:133)
	at meghanada.junit.TestRunner.<init>(TestRunner.java:43)
	at meghanada.junit.TestRunner.main(TestRunner.java:50)

**Comment by iocanel** [comment]
FWIW, the issue is caused, due to a version conflict between the 'hosted' project and meghanada itself. 

It seems that the meghanada TestRunner, is adding to the test classpath all the dependencies of the 'hosted' project. So, there can be conflicts.

This needs to be documented.

The issue could be possibly fixed by using relocation of the shaded classes. I tried it and it didn't work out, but then again my gradle-FU is limited.

**Comment by xqliu** [comment]
Is it possible to fork a new JVM process to run the test and set classpath separately rather than mix the host server with test runner?

Thanks.

**Comment by mopemope** [comment]
There is no problem because the test runner 's JVM has forked already.
