### ISSUE TITLE
java.lang.IllegalArgumentException: 无效的源发行版: ${java.version}

### ISSUE THREAD

**Issue by sound2gd** [mopemope/meghanada-server#5]
when I start meghanda server ,I got this error, and everything works fine except "extract local variables, auto import . 
java.lang.IllegalArgumentException: 无效的源发行版: ${java.version}
	at com.sun.tools.javac.main.OptionHelper$GrumpyHelper.error(OptionHelper.java:103) ~[?:?]
	at com.sun.tools.javac.main.Option$11.process(Option.java:204) ~[?:?]
	at com.sun.tools.javac.api.JavacTool.processOptions(JavacTool.java:217) ~[?:?]
	at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:156) ~[?:?]
	at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:107) ~[?:?]
	at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:64) ~[?:?]
	at meghanada.compiler.SimpleJavaCompiler.compileFiles(SimpleJavaCompiler.java:61) ~[meghanada-0.2.4.jar:?]
	at meghanada.project.Project.compileJava(Project.java:207) ~[meghanada-0.2.4.jar:?]
	at meghanada.session.subscribe.CacheEventSubscriber.lambda$on$0(CacheEventSubscriber.java:45) ~[meghanada-0.2.4.jar:?]
	at meghanada.config.Config.timeItF(Config.java:86) [meghanada-0.2.4.jar:?]
	at meghanada.session.subscribe.CacheEventSubscriber.on(CacheEventSubscriber.java:43) [meghanada-0.2.4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:95) [meghanada-0.2.4.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:154) [meghanada-0.2.4.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:80) [meghanada-0.2.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

**Comment by mopemope** [comment]
@sound2gd I have fixed it. Please check latest version.
