### ISSUE TITLE
Error starting server

### ISSUE THREAD

**Issue by oleorhagen** [mopemope/meghanada-server#71]
jdk: 10
command run:
java -jar meghanada-1.0.8.jar
Error:
`[2018-09-09 13:15:48,603][INFO ][Main      : 130] Meghanada-Server Version:1.0.8-3297bd8
[2018-09-09 13:15:48,619][ERROR][EmacsServe: 369] Catching
java.lang.IllegalArgumentException: Project Not Found
	at meghanada.session.Session.lambda$createSession$0(Session.java:106) ~[meghanada-1.0.8.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:397) ~[?:?]
	at meghanada.session.Session.createSession(Session.java:106) ~[meghanada-1.0.8.jar:?]
	at meghanada.session.Session.createSession(Session.java:98) ~[meghanada-1.0.8.jar:?]
	at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:363) [meghanada-1.0.8.jar:?]
	at meghanada.Main.main(Main.java:132) [meghanada-1.0.8.jar:?]
[2018-09-09 13:15:48,627][INFO ][Main      :  69] shutdown server
[2018-09-09 13:15:48,629][INFO ][Config    : 198] memory usage (used/total/max): 16.00MB / 62.00MB / 964.00MB
`

**Comment by mopemope** [comment]
@oleorhagen Go to the root directory of the project and execute the command.
