### ISSUE TITLE
NPE in DeclarationSearcher.searchMethodCall

### ISSUE THREAD

**Issue by jypma** [mopemope/meghanada-server#73]
Somehow, one of the `arguments` apparently ends up being null:
```
[2018-10-02 12:48:22,048][ERROR][CommandHan:  49] Catching
java.lang.NullPointerException: null
	at meghanada.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877) ~[meghanada-1.0.9.jar:?]
	at meghanada.com.google.common.base.Joiner.toString(Joiner.java:452) ~[meghanada-1.0.9.jar:?]
	at meghanada.com.google.common.base.Joiner.appendTo(Joiner.java:106) ~[meghanada-1.0.9.jar:?]
	at meghanada.com.google.common.base.Joiner.appendTo(Joiner.java:152) ~[meghanada-1.0.9.jar:?]
	at meghanada.com.google.common.base.Joiner.join(Joiner.java:195) ~[meghanada-1.0.9.jar:?]
	at meghanada.com.google.common.base.Joiner.join(Joiner.java:185) ~[meghanada-1.0.9.jar:?]
	at meghanada.docs.declaration.DeclarationSearcher.lambda$searchMethodCall$6(DeclarationSearcher.java:176) ~[meghanada-1.0.9.jar:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_172]
	at meghanada.docs.declaration.DeclarationSearcher.searchMethodCall(DeclarationSearcher.java:159) ~[meghanada-1.0.9.jar:?]
	at meghanada.docs.declaration.DeclarationSearcher.execFunctions(DeclarationSearcher.java:251) ~[meghanada-1.0.9.jar:?]
	at meghanada.docs.declaration.DeclarationSearcher.lambda$searchDeclaration$9(DeclarationSearcher.java:267) ~[meghanada-1.0.9.jar:?]
	at java.util.Optional.flatMap(Optional.java:241) ~[?:1.8.0_172]
	at meghanada.docs.declaration.DeclarationSearcher.searchDeclaration(DeclarationSearcher.java:267) ~[meghanada-1.0.9.jar:?]
	at meghanada.session.Session.showDeclaration(Session.java:819) ~[meghanada-1.0.9.jar:?]
	at meghanada.server.CommandHandler.showDeclaration(CommandHandler.java:361) ~[meghanada-1.0.9.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$21(EmacsServer.java:265) ~[meghanada-1.0.9.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-1.0.9.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-1.0.9.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-1.0.9.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:363) ~[meghanada-1.0.9.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$36(EmacsServer.java:444) ~[meghanada-1.0.9.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
```

**Comment by mopemope** [comment]
@jypma It is strange that arguments should not be null ...
