### ISSUE TITLE
Add support for Java11

### ISSUE THREAD

**Issue by prassee** [mopemope/meghanada-server#77]
With Java11 being the next stable release , add support for Java11.

**Comment by sunng87** [comment]
When using meghanada on Java 11, I'm getting error during indexing:

>[2019-01-20 00:07:20,328][ERROR][SystemEven:  28] Catching
java.lang.RuntimeException: java.lang.UnsupportedOperationException: This feature requires ASM7
	at meghanada.config.Config.timeItF(Config.java:135) ~[meghanada-1.0.11.jar:?]
	at meghanada.session.subscribe.CacheEventSubscriber.analyze(CacheEventSubscriber.java:56) ~[meghanada-1.0.11.jar:?]
	at meghanada.session.subscribe.CacheEventSubscriber.on(CacheEventSubscriber.java:32) ~[meghanada-1.0.11.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at meghanada.com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87) ~[meghanada-1.0.11.jar:?]
	at meghanada.com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144) ~[meghanada-1.0.11.jar:?]
	at meghanada.com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72) ~[meghanada-1.0.11.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: java.lang.UnsupportedOperationException: This feature requires ASM7
	at meghanada.org.objectweb.asm.ClassVisitor.visitNestMember(ClassVisitor.java:236) ~[meghanada-1.0.11.jar:?]
	at meghanada.org.objectweb.asm.ClassReader.accept(ClassReader.java:651) ~[meghanada-1.0.11.jar:?]
	at meghanada.org.objectweb.asm.ClassReader.accept(ClassReader.java:391) ~[meghanada-1.0.11.jar:?]
	at meghanada.reflect.asm.ASMReflector.readClassIndex(ASMReflector.java:169) ~[meghanada-1.0.11.jar:?]
	at meghanada.reflect.asm.ASMReflector.lambda$getClasses$2(ASMReflector.java:288) ~[meghanada-1.0.11.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at meghanada.reflect.asm.ASMReflector.lambda$getClasses$3(ASMReflector.java:280) ~[meghanada-1.0.11.jar:?]
	at meghanada.module.ModuleHelper.walkModuleFS(ModuleHelper.java:66) ~[meghanada-1.0.11.jar:?]
	at meghanada.module.ModuleHelper.walkModuleFS(ModuleHelper.java:62) ~[meghanada-1.0.11.jar:?]
	at meghanada.module.ModuleHelper.walkModuleFS(ModuleHelper.java:62) ~[meghanada-1.0.11.jar:?]
	at meghanada.module.ModuleHelper.walkModuleFS(ModuleHelper.java:62) ~[meghanada-1.0.11.jar:?]
	at meghanada.module.ModuleHelper.walkModuleFS(ModuleHelper.java:62) ~[meghanada-1.0.11.jar:?]
	at meghanada.module.ModuleHelper.walkModule(ModuleHelper.java:36) ~[meghanada-1.0.11.jar:?]
	at meghanada.reflect.asm.ASMReflector.getClasses(ASMReflector.java:277) ~[meghanada-1.0.11.jar:?]
	at meghanada.reflect.asm.CachedASMReflector.lambda$updateClassIndexFromDirectory$7(CachedASMReflector.java:270) ~[meghanada-1.0.11.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIOConsumer$2(FunctionUtils.java:34) ~[meghanada-1.0.11.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[?:?]

This is pretty weird because I found meghanada is already using asm 7.0
