### ISSUE TITLE
FileNotFoundException in lucene

### ISSUE THREAD

**Issue by alexeiz** [mopemope/meghanada-server#79]
I get a lot of exceptions like this:

```
 [2018-12-28 09:51:45,419][ERROR][SystemEven:  28] Catching
 java.io.UncheckedIOException: java.io.FileNotFoundException: _44d.cfs
     at meghanada.index.DocumentSearcher.lambda$executeInTransaction$2(DocumentSearcher.java:164) ~[meghanada-1.0.10.jar:?]
     at jetbrains.exodus.env.EnvironmentImpl.executeInTransaction(EnvironmentImpl.java:1005) ~[meghanada-1.0.10.jar:?]
     at jetbrains.exodus.env.EnvironmentImpl.executeInTransaction(EnvironmentImpl.java:257) ~[meghanada-1.0.10.jar:?]
     at jetbrains.exodus.env.ContextualEnvironmentImpl.executeInTransaction(ContextualEnvironmentImpl.java:131) ~[meghanada-1.0.10.jar:?]
     at meghanada.index.DocumentSearcher.executeInTransaction(DocumentSearcher.java:155) ~[meghanada-1.0.10.jar:?]
     at meghanada.index.IndexDatabase.indexObject(IndexDatabase.java:95) ~[meghanada-1.0.10.jar:?]
     at meghanada.index.IndexDatabase.on(IndexDatabase.java:136) ~[meghanada-1.0.10.jar:?]
     at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
     at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
     at meghanada.com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87) ~[meghanada-1.0.10.jar:?]
     at meghanada.com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144) ~[meghanada-1.0.10.jar:?]
     at meghanada.com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72) [meghanada-1.0.10.jar:?]
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
     at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
 Caused by: java.io.FileNotFoundException: _44d.cfs
     at jetbrains.exodus.lucene.ExodusDirectory.openInput(ExodusDirectory.java:115) ~[meghanada-1.0.10.jar:?]
     at org.apache.lucene.store.Directory.openInput(Directory.java:145) ~[meghanada-1.0.10.jar:?]
     at org.apache.lucene.index.CompoundFileReader.<init>(CompoundFileReader.java:65) ~[meghanada-1.0.10.jar:?]
     at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:75) ~[meghanada-1.0.10.jar:?]
     at org.apache.lucene.index.SegmentReader.get(SegmentReader.java:116) ~[meghanada-1.0.10.jar:?]
     at org.apache.lucene.index.IndexWriter$ReaderPool.get(IndexWriter.java:696) ~[meghanada-1.0.10.jar:?]
     at org.apache.lucene.index.IndexWriter$ReaderPool.get(IndexWriter.java:671) ~[meghanada-1.0.10.jar:?]
     at org.apache.lucene.index.BufferedDeletesStream.applyDeletes(BufferedDeletesStream.java:244) ~[meghanada-1.0.10.jar:?]
     at org.apache.lucene.index.IndexWriter.doFlush(IndexWriter.java:3615) ~[meghanada-1.0.10.jar:?]
     at org.apache.lucene.index.IndexWriter.flush(IndexWriter.java:3552) ~[meghanada-1.0.10.jar:?]
     at org.apache.lucene.index.IndexWriter.closeInternal(IndexWriter.java:1852) ~[meghanada-1.0.10.jar:?]
     at org.apache.lucene.index.IndexWriter.close(IndexWriter.java:1812) ~[meghanada-1.0.10.jar:?]
     at org.apache.lucene.index.IndexWriter.close(IndexWriter.java:1776) ~[meghanada-1.0.10.jar:?]
     at meghanada.index.DocumentSearcher.closeIndexWriter(DocumentSearcher.java:95) ~[meghanada-1.0.10.jar:?]
     at meghanada.index.DocumentSearcher.lambda$executeInTransaction$2(DocumentSearcher.java:161) ~[meghanada-1.0.10.jar:?]
     ... 15 more
```

Meghanada server starts fine and works for a while, but eventually exceptions with the above stack trace start happening, slowing down emacs meghanada client to a crawl.  Note that the file name which is not found (_44d.cfs) differs from session to session.

**Comment by mopemope** [comment]
I think it is a problem of lucene. i can not reproduce it.
@alexeiz Does this happen even with the latest version?
