### ISSUE TITLE
NullPointerException during autocomplete causing client to disconnect from server

### ISSUE THREAD

**Issue by dakrone** [mopemope/meghanada-server#8]
Here's the stacktrace from the server buffer:

```
[2017-02-02 16:16:55,464][ERROR][EmacsServer   : 138] lambda$acceptConnectio - Catching
java.lang.RuntimeException: java.lang.NullPointerException
	at meghanada.server.CommandHandler.autocomplete(CommandHandler.java:101) ~[meghanada-0.5.0.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$5(EmacsServer.java:169) ~[meghanada-0.5.0.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-0.5.0.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-0.5.0.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-0.5.0.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:271) ~[meghanada-0.5.0.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$2(EmacsServer.java:125) ~[meghanada-0.5.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at meghanada.utils.ClassNameUtils.getSimpleName(ClassNameUtils.java:169) ~[meghanada-0.5.0.jar:?]
	at meghanada.reflect.FieldDescriptor.getDisplayDeclaration(FieldDescriptor.java:49) ~[meghanada-0.5.0.jar:?]
	at meghanada.server.formatter.SexpOutputFormatter.lambda$autocomplete$1(SexpOutputFormatter.java:88) ~[meghanada-0.5.0.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_111]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_111]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_111]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_111]
	at meghanada.server.formatter.SexpOutputFormatter.autocomplete(SexpOutputFormatter.java:91) ~[meghanada-0.5.0.jar:?]
	at meghanada.server.CommandHandler.autocomplete(CommandHandler.java:97) ~[meghanada-0.5.0.jar:?]
	... 11 more
[2017-02-02 16:16:55,469][INFO ][EmacsServer   : 145] lambda$acceptConnectio - client disconnect
```

**Comment by mopemope** [comment]
@dakrone Thank you for your reoirt. Could you tell me the completion class FQCN ?

**Comment by dakrone** [comment]
I will try to reproduce it so I can see where I was when this occurred (I have seen it a number of times)

**Comment by mopemope** [comment]
@dakrone any update on this?

**Comment by dakrone** [comment]
@mopemope I am still getting NPEs causing meghanada to crash, here's the latest one from earlier today:

```
[2017-05-08 11:21:33,350][ERROR][CommandHandler:  61] diagnostics            - Catching
java.lang.NullPointerException: null
	at meghanada.analyze.TreeAnalyzer.getTypeString(TreeAnalyzer.java:853) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.analyzeLambda(TreeAnalyzer.java:720) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.analyzeParsedTree(TreeAnalyzer.java:553) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.lambda$getArgumentsType$26(TreeAnalyzer.java:1077) ~[meghanada-0.7.5.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_111]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_111]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_111]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_111]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_111]
	at meghanada.analyze.TreeAnalyzer.getArgumentsType(TreeAnalyzer.java:1084) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.analyzeMethodInvocation(TreeAnalyzer.java:889) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.analyzeParsedTree(TreeAnalyzer.java:498) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.lambda$analyzeExpressionStatement$28(TreeAnalyzer.java:1118) ~[meghanada-0.7.5.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIOConsumer$2(FunctionUtils.java:34) ~[meghanada-0.7.5.jar:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_111]
	at meghanada.analyze.TreeAnalyzer.analyzeExpressionStatement(TreeAnalyzer.java:1097) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.analyzeParsedTree(TreeAnalyzer.java:420) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.lambda$analyzeParsedTree$3(TreeAnalyzer.java:399) ~[meghanada-0.7.5.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIOConsumer$2(FunctionUtils.java:34) ~[meghanada-0.7.5.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_111]
	at meghanada.analyze.TreeAnalyzer.analyzeParsedTree(TreeAnalyzer.java:398) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.lambda$analyzeMethodDecl$52(TreeAnalyzer.java:1470) ~[meghanada-0.7.5.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIOConsumer$2(FunctionUtils.java:34) ~[meghanada-0.7.5.jar:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_111]
	at meghanada.analyze.TreeAnalyzer.analyzeMethodDecl(TreeAnalyzer.java:1422) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.analyzeParsedTree(TreeAnalyzer.java:387) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.lambda$analyzeCompilationUnitTree$2(TreeAnalyzer.java:338) ~[meghanada-0.7.5.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIOConsumer$2(FunctionUtils.java:34) ~[meghanada-0.7.5.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_111]
	at meghanada.analyze.TreeAnalyzer.analyzeCompilationUnitTree(TreeAnalyzer.java:338) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.analyzeUnit(TreeAnalyzer.java:1625) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.lambda$analyze$57(TreeAnalyzer.java:1591) ~[meghanada-0.7.5.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIOConsumer$2(FunctionUtils.java:34) ~[meghanada-0.7.5.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_111]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_111]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[?:1.8.0_111]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:405) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) ~[?:1.8.0_111]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) ~[?:1.8.0_111]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:1.8.0_111]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_111]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583) ~[?:1.8.0_111]
	at meghanada.analyze.TreeAnalyzer.analyze(TreeAnalyzer.java:1590) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.JavaAnalyzer.runAnalyzeAndCompile(JavaAnalyzer.java:134) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.JavaAnalyzer.analyzeAndCompile(JavaAnalyzer.java:87) ~[meghanada-0.7.5.jar:?]
	at meghanada.project.Project.compileTestJava(Project.java:282) ~[meghanada-0.7.5.jar:?]
	at meghanada.project.gradle.GradleProject.compileTestJava(GradleProject.java:371) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.Session.compileProject(Session.java:495) ~[meghanada-0.7.5.jar:?]
	at meghanada.server.CommandHandler.diagnostics(CommandHandler.java:56) ~[meghanada-0.7.5.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$9(EmacsServer.java:193) ~[meghanada-0.7.5.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-0.7.5.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-0.7.5.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-0.7.5.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:277) ~[meghanada-0.7.5.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$2(EmacsServer.java:125) ~[meghanada-0.7.5.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[2017-05-08 11:21:33,407][ERROR][EmacsServer   : 138] lambda$acceptConnectio - Catching
meghanada.server.CommandException: java.lang.NullPointerException
	at meghanada.server.CommandHandler.diagnostics(CommandHandler.java:62) ~[meghanada-0.7.5.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$9(EmacsServer.java:193) ~[meghanada-0.7.5.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-0.7.5.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-0.7.5.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-0.7.5.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:277) ~[meghanada-0.7.5.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$2(EmacsServer.java:125) ~[meghanada-0.7.5.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at meghanada.analyze.TreeAnalyzer.getTypeString(TreeAnalyzer.java:853) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.analyzeLambda(TreeAnalyzer.java:720) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.analyzeParsedTree(TreeAnalyzer.java:553) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.lambda$getArgumentsType$26(TreeAnalyzer.java:1077) ~[meghanada-0.7.5.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_111]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_111]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_111]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_111]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_111]
	at meghanada.analyze.TreeAnalyzer.getArgumentsType(TreeAnalyzer.java:1084) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.analyzeMethodInvocation(TreeAnalyzer.java:889) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.analyzeParsedTree(TreeAnalyzer.java:498) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.lambda$analyzeExpressionStatement$28(TreeAnalyzer.java:1118) ~[meghanada-0.7.5.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIOConsumer$2(FunctionUtils.java:34) ~[meghanada-0.7.5.jar:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_111]
	at meghanada.analyze.TreeAnalyzer.analyzeExpressionStatement(TreeAnalyzer.java:1097) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.analyzeParsedTree(TreeAnalyzer.java:420) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.lambda$analyzeParsedTree$3(TreeAnalyzer.java:399) ~[meghanada-0.7.5.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIOConsumer$2(FunctionUtils.java:34) ~[meghanada-0.7.5.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_111]
	at meghanada.analyze.TreeAnalyzer.analyzeParsedTree(TreeAnalyzer.java:398) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.lambda$analyzeMethodDecl$52(TreeAnalyzer.java:1470) ~[meghanada-0.7.5.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIOConsumer$2(FunctionUtils.java:34) ~[meghanada-0.7.5.jar:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_111]
	at meghanada.analyze.TreeAnalyzer.analyzeMethodDecl(TreeAnalyzer.java:1422) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.analyzeParsedTree(TreeAnalyzer.java:387) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.lambda$analyzeCompilationUnitTree$2(TreeAnalyzer.java:338) ~[meghanada-0.7.5.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIOConsumer$2(FunctionUtils.java:34) ~[meghanada-0.7.5.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_111]
	at meghanada.analyze.TreeAnalyzer.analyzeCompilationUnitTree(TreeAnalyzer.java:338) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.analyzeUnit(TreeAnalyzer.java:1625) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.TreeAnalyzer.lambda$analyze$57(TreeAnalyzer.java:1591) ~[meghanada-0.7.5.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIOConsumer$2(FunctionUtils.java:34) ~[meghanada-0.7.5.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_111]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_111]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[?:1.8.0_111]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:405) ~[?:1.8.0_111]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) ~[?:1.8.0_111]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) ~[?:1.8.0_111]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) ~[?:1.8.0_111]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:1.8.0_111]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_111]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583) ~[?:1.8.0_111]
	at meghanada.analyze.TreeAnalyzer.analyze(TreeAnalyzer.java:1590) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.JavaAnalyzer.runAnalyzeAndCompile(JavaAnalyzer.java:134) ~[meghanada-0.7.5.jar:?]
	at meghanada.analyze.JavaAnalyzer.analyzeAndCompile(JavaAnalyzer.java:87) ~[meghanada-0.7.5.jar:?]
	at meghanada.project.Project.compileTestJava(Project.java:282) ~[meghanada-0.7.5.jar:?]
	at meghanada.project.gradle.GradleProject.compileTestJava(GradleProject.java:371) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.Session.compileProject(Session.java:495) ~[meghanada-0.7.5.jar:?]
	at meghanada.server.CommandHandler.diagnostics(CommandHandler.java:56) ~[meghanada-0.7.5.jar:?]
	... 11 more
[2017-05-08 11:21:33,415][INFO ][EmacsServer   : 145] lambda$acceptConnectio - client disconnect
```

**Comment by mopemope** [comment]
@dakrone Thank you for your report.
