### ISSUE TITLE
meghanada-emacs causes sentinel and Disconnected:meghanada-client error

### ISSUE THREAD

**Issue by romario89** [mopemope/meghanada-server#81]
Emacs-25.2.1 on Windows XP, meghanada-emacs 0.9 and meghanada-server. I have successfully built `meghanada-1.0.9.jar` with `./gradlew clean goJF check shadowJar` I'm using `jdk-1.8.0_131` and meghanada as standalone application i.e. `java -jar server/build/libs/meghanada-1.0.9.jar` runs perfectly.
 
But when I try to run meghanada-server from within Emacs, I get the following error. 

    [INFO ][Main      : 130] Meghanada-Server Version:1.0.9-release
    [INFO ][Session   : 179] load project from cache. projectRoot:C:\Documents and Settings\x41\java\SKELETON
    [INFO ][EmacsServe: 381] Start server Listen localhost port:1596
    [INFO ][EmacsServe: 403] client connected
    [INFO ][Config    : 135] create class index ... read 1 jars. elapsed:775.6 ms
    [INFO ][CacheEvent:  67] start analyze sources ...
    [INFO ][Project   : 310] project SKELETON compile and analyze (java) 1 files. force:true problem:0 elapsed:1.527 s
    [INFO ][Config    : 135] analyzed and compiled. elapsed:1.568 s
    [INFO ][CacheEvent:  93] class index size:5605 total elapsed:2.363 s
    [INFO ][Config    : 198] memory usage (used/total/max): 55,00MB / 123,00MB / 247,00MB
    [INFO ][CacheEvent:  98] Ready
    [ERROR][EmacsServe: 457] Catching
    java.lang.NumberFormatException: For input string: "and"
	    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_131]
    	<truncated>
    [INFO ][EmacsServe: 464] client disconnect

Changing the position of cursor (e.g. going down to next line , going right to the next letter) is enough to bring about this error. And here is the most problematic part: I get Emacs sentinel error: `error in process sentinel: Disconnected:meghanada-client process stopped: connection broken by remote peer` 
and emacs.exe process begins to take 100% CPU load and only C-G can end this.

After I close the Emacs, the meghanada-server's java.exe process quits gracefully. No problems there.

I've tried with meghanada-emacs **0.13** and meghanada-server (meghanada **-1.0.13** .jar) and
the problem's the same

1- How to prevent from Emacs causing sentinel process?
2- How to deal with the  `java.lang.NumberFormatException: For input string: "and"` error? Should I 
 rebuild `meghanada-XXX.jar` using some other settings?
Thank you.

**Comment by mopemope** [comment]
Could you write all stack traces if possible?

**Comment by romario89** [comment]
Thank you for your interest. Here is the complete stack trace:

[meghanada-server-log-20190330.txt @ Pastebin](https://pastebin.com/zjV1xqfC)
And here is the Meghanada startup script, which I got by modifying the `meghanada--start-server-process` function in `meghanda.el` 
![meghanada startup](http://i66.tinypic.com/14jm5hz.png)

**Comment by paulopicasso** [comment]
I've got the same problem. Windows 10 and Spacemacs on Emacs 26.2

**Comment by romario89** [comment]
> 
> 
> I've got the same problem. Windows 10 and Spacemacs on Emacs 26.2

Could you send the complete stack traces? It's on the buffer named `*meghanada-server-log*`
And here is my whole stack trace for completeness:
``
﻿[2019-03-30 13:05:11,765][INFO ][Main      : 130] Meghanada-Server Version:1.0.9-release
[2019-03-30 13:05:15,343][INFO ][Session   : 210] loaded project:C:\Documents and Settings\x41\java\SKELETON elapsed:102.6 ms
[2019-03-30 13:05:16,046][INFO ][EmacsServe: 381] Start server Listen localhost port:1073
[2019-03-30 13:05:17,015][INFO ][EmacsServe: 403] client connected
[2019-03-30 13:05:19,031][INFO ][Config    : 135] create class index ... read 1 jars. elapsed:2.981 s
[2019-03-30 13:05:19,031][INFO ][CacheEvent:  67] start analyze sources ...
[2019-03-30 13:05:22,500][INFO ][Project   : 310] project SKELETON compile and analyze (java) 1 files. force:true problem:0 elapsed:3.464 s
[2019-03-30 13:05:22,515][INFO ][Config    : 135] analyzed and compiled. elapsed:3.472 s
[2019-03-30 13:05:22,515][INFO ][CacheEvent:  93] class index size:4693 total elapsed:6.462 s
[2019-03-30 13:05:22,515][INFO ][Config    : 198] memory usage (used/total/max): 69,00MB / 123,00MB / 247,00MB
[2019-03-30 13:05:22,515][INFO ][CacheEvent:  98] Ready
[2019-03-30 13:05:26,531][ERROR][EmacsServe: 457] Catching
java.lang.NumberFormatException: For input string: "and"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_153]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_153]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_153]
	at meghanada.server.CommandHandler.showDeclaration(CommandHandler.java:356) ~[meghanada-1.0.9.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$21(EmacsServer.java:265) ~[meghanada-1.0.9.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-1.0.9.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-1.0.9.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-1.0.9.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:363) ~[meghanada-1.0.9.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$36(EmacsServer.java:444) ~[meghanada-1.0.9.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_153]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_153]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_153]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_153]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_153]
[2019-03-30 13:05:26,656][INFO ][EmacsServe: 464] client disconnect

;; .emacs file

;; Meghanada Mode START

(add-to-list 'load-path "~/.emacs.d/elpa/meghanada-emacs-1.0.9/")

(require 'meghanada)

(setq meghanada-start "java -jar server/build/libs/meghanada-1.0.13.jar")

(add-hook 'java-mode-hook
          (lambda ()
            ;; meghanada-mode on
            (meghanada-mode t)
            (flycheck-mode +1)
            (setq c-basic-offset 2)
            ;; use code format
            (add-hook 'before-save-hook 'meghanada-code-beautify-before-save)))
(cond
   ((eq system-type 'windows-nt)
    (setq meghanada-java-path
	  (expand-file-name "bin/java.exe" (getenv "ZULU8"))
	  ;; Ja natürlich wird es bin/java.exe
	  ;; ins Ende hinzufügen. Ganz logisch!
	  )
    (setq meghanada-maven-path "mvn.cmd"))
   (t
    (setq meghanada-java-path "java")
    (setq meghanada-maven-path "mvn")))

;; Meghanada Mode END ;;``

**Comment by mopemope** [comment]
Hmmm. Does this problem only occur on Windows?

**Comment by romario89** [comment]
I've used and tried Meghanada only on Windows 7 and XP so far. I haven't tried it on any other platform. This and the @paulopicasso 's message indicate that this problem seems to occur particularly on Windows.

**Comment by mopemope** [comment]
Thank you for your reply. `meghanada--what-line` seems to have a problem... I will try to rewrite it in the next version, so please try it.

**Comment by romario89** [comment]
Thank you for the patch. I've applied the patch (i.e. edited the `meghanada--what-line` function and byte compiled the `meghanada.el` but the problem seems to be the same. Here is the log:

[2019-05-10 18:07:22,046][INFO ][Main      : 130] Meghanada-Server Version:1.0.9-release
[2019-05-10 18:07:27,703][INFO ][Session   : 179] load project from cache. projectRoot:C:\Documents and Settings\x41\java\SKELETON
[2019-05-10 18:07:28,296][INFO ][EmacsServe: 381] Start server Listen localhost port:1796
[2019-05-10 18:07:29,015][INFO ][EmacsServe: 403] client connected
[2019-05-10 18:07:29,218][INFO ][Config    : 135] create class index ... read 0 jars. elapsed:879.8 ms
[2019-05-10 18:07:29,234][INFO ][CacheEvent:  67] start analyze sources ...
[2019-05-10 18:07:31,312][INFO ][Project   : 310] project SKELETON compile and analyze (java) 1 files. force:true problem:0 elapsed:2.076 s
[2019-05-10 18:07:31,312][INFO ][Config    : 135] analyzed and compiled. elapsed:2.084 s
[2019-05-10 18:07:31,312][INFO ][CacheEvent:  93] class index size:4665 total elapsed:3.040 s
[2019-05-10 18:07:31,312][INFO ][Config    : 198] memory usage (used/total/max): 47,00MB / 123,00MB / 247,00MB
[2019-05-10 18:07:31,312][INFO ][CacheEvent:  98] Ready
[2019-05-10 18:07:50,578][WARN ][JavaSource:  74] source cache miss C:\Documents and Settings\x41\java\SKELETON\src\.#TRY.java
[2019-05-10 18:07:52,421][ERROR][CommandHan:  49] Catching
java.io.FileNotFoundException: File 'and' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299) ~[meghanada-1.0.9.jar:?]
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1711) ~[meghanada-1.0.9.jar:?]
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1748) ~[meghanada-1.0.9.jar:?]
	at meghanada.server.CommandHandler.diagnostics(CommandHandler.java:89) ~[meghanada-1.0.9.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$9(EmacsServer.java:161) ~[meghanada-1.0.9.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-1.0.9.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-1.0.9.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-1.0.9.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:363) ~[meghanada-1.0.9.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$36(EmacsServer.java:444) ~[meghanada-1.0.9.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_153]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_153]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_153]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_153]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_153]
[2019-05-10 18:07:52,468][INFO ][EmacsServe: 365] receive command [dl, C:\Documents, and, Settings\x41\java\SKELETON\src\TRY.java, C:\Documents, and, Settings\x41\Local, Settings\Temp\meghanada752p0x.java]. elapsed:155.0 ms
[2019-05-10 18:07:56,812][ERROR][CommandHan:  49] Catching
java.io.FileNotFoundException: File 'and' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299) ~[meghanada-1.0.9.jar:?]
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1711) ~[meghanada-1.0.9.jar:?]
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1748) ~[meghanada-1.0.9.jar:?]
	at meghanada.server.CommandHandler.diagnostics(CommandHandler.java:89) ~[meghanada-1.0.9.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$9(EmacsServer.java:161) ~[meghanada-1.0.9.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-1.0.9.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-1.0.9.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-1.0.9.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:363) ~[meghanada-1.0.9.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$36(EmacsServer.java:444) ~[meghanada-1.0.9.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_153]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_153]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_153]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_153]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_153]
[2019-05-10 18:07:56,828][INFO ][EmacsServe: 365] receive command [dl, C:\Documents, and, Settings\x41\java\SKELETON\src\TRY.java, C:\Documents, and, Settings\x41\Local, Settings\Temp\meghanada752b-A.java]. elapsed:2.349 ms
[2019-05-10 18:07:56,828][ERROR][EmacsServe: 457] Catching
java.lang.NumberFormatException: For input string: "and"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_153]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_153]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_153]
	at meghanada.server.CommandHandler.showDeclaration(CommandHandler.java:356) ~[meghanada-1.0.9.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$21(EmacsServer.java:265) ~[meghanada-1.0.9.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-1.0.9.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-1.0.9.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-1.0.9.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:363) ~[meghanada-1.0.9.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$36(EmacsServer.java:444) ~[meghanada-1.0.9.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_153]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_153]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_153]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_153]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_153]
[2019-05-10 18:07:56,828][INFO ][EmacsServe: 464] client disconnect

**Comment by mopemope** [comment]
I understand the cause.  I will fix it soon.
