### ISSUE TITLE
Exception in thread "pool-3-thread-1" java.lang.NoClassDefFoundError: Lcom/sun/source/tree/LineMap; 

### ISSUE THREAD

**Issue by johnutz-self** [mopemope/meghanada-server#89]
OS:    Win 10  Pro Bld 1803
JAVA: 1.8u211 (build 1.8.0_211-b12)

.meghanada.conf:
java-home = "$JAVA_HOME"
java-version = "1.8"
compile-source = "1.8"
compile-target = "1.8"
java11-javac-args = [
                 "--add-exports",
                 "jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED",
                 "--add-exports",
                 "jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED",
                 "--add-exports",
                 "jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED",
                 "--add-exports",
                 "jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED",
                 "--add-exports",
                 "jdk.compiler/com.sun.tools.javac.resources=ALL-UNNAMED",
                 "--add-exports",
                 "jdk.compiler/com.sun.tools.javac.resources=ALL-UNNAMED",
                 "--add-exports",
                 "java.management/sun.management=ALL-UNNAMED",
]
dependencies = ["C:/PTC/Creo 3.0/M150/Common Files/text/java/pfc.jar" ... ]
sources = ["pensar/me/dimid"]
resources = ["text/usascii/resource"]
output = "build/classes"
test-output = "build/test/classes"

Issue:
attempting to parse the project java files located at pensar\me\dimid results in the stack trace listed below:
(emacs meghanada-server-log and commandline invocation have identical results)

$ java -jar ..\..\.emacs.d\meghanada\meghanada-1.1.2.jar                                                                  
[INFO ][Main      :  53] use java home: C:\Program Files\Java\jre1.8.0_211                                                
[INFO ][Main      :  54] use java runtime: Java(TM) SE Runtime Environment 1.8.0_211-b12                                  
[INFO ][Main      :  58] use java vm: Java HotSpot(TM) 64-Bit Server VM 25.211-b12                                        
[INFO ][Session   : 221] loaded project:C:\Users\john.utz\GIT\AutoDimID elapsed:2.441 ms                                  
Exception in thread "pool-3-thread-1" java.lang.NoClassDefFoundError: Lcom/sun/source/tree/LineMap;                       
        at java.lang.Class.getDeclaredFields0(Native Method)                                                              
        at java.lang.Class.privateGetDeclaredFields(Unknown Source)                                                       
        at java.lang.Class.getDeclaredFields(Unknown Source)                                                              
        at org.nustaq.serialization.FSTClazzInfo.getAllFields(FSTClazzInfo.java:249)                                      
        at org.nustaq.serialization.FSTClazzInfo.createFields(FSTClazzInfo.java:355)                                      
        at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:127)                                            
        at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:129)                         
        at org.nustaq.serialization.FSTClazzNameRegistry.addClassMapping(FSTClazzNameRegistry.java:98)                    
        at org.nustaq.serialization.FSTClazzNameRegistry.registerClassNoLookup(FSTClazzNameRegistry.java:85)              
        at org.nustaq.serialization.FSTClazzNameRegistry.registerClass(FSTClazzNameRegistry.java:81)                      
        at org.nustaq.serialization.FSTConfiguration.registerClass(FSTConfiguration.java:788)                             
        at meghanada.store.Serializer.getFST(Serializer.java:46)                                                          
        at meghanada.store.Serializer.asByte(Serializer.java:122)                                                         
        at meghanada.store.ProjectDatabase.setSerializeBlobData(ProjectDatabase.java:194)                                 
        at meghanada.store.ProjectDatabase.putObject(ProjectDatabase.java:175)                                            
        at meghanada.store.ProjectDatabase.lambda$storeObjects$4(ProjectDatabase.java:459)                                
        at jetbrains.exodus.entitystore.PersistentEntityStoreImpl.computeInTransaction(PersistentEntityStoreImpl.java:738)
        at meghanada.store.ProjectDatabase.storeObjects(ProjectDatabase.java:455)                                         
        at meghanada.store.ProjectDatabase.mergeAndStore(ProjectDatabase.java:265)                                        
        at meghanada.store.ProjectDatabase.lambda$initWorker$1(ProjectDatabase.java:224)                                  
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)                                              
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)                                             
        at java.lang.Thread.run(Unknown Source)                                                                           
Caused by: java.lang.ClassNotFoundException: com.sun.source.tree.LineMap                                                  
        at java.net.URLClassLoader.findClass(Unknown Source)                                                              
        at java.lang.ClassLoader.loadClass(Unknown Source)                                                                
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)                                                     
        at java.lang.ClassLoader.loadClass(Unknown Source)                                                                
        ... 23 more       

Is there some  additional jar path or dependency information that i need to provide to resolve this issue? Please let me know.

Tnx!

johnu

**Comment by mopemope** [comment]
@johnutz-self Please check  the latest version, and your `tools.jar` path and `*meghanada-server-log*`  buffer.

**Comment by johnutz-self** [comment]
Thankyou for the suggestions, I will add tools.jar to y classpath. I am not seeing anything about tools.jar in the documentation, did i  miss it somehow? Are there any other things that are needed in my classpath for the successful operation of meghanada server?

**Comment by johnutz-self** [comment]
figured out the issue!
my .meghanada,conf java-home variable did not work because I am running this on windows:

This is what is needed to work successfully:

java-home = "/Program Files/Java/jdk1.8.0_211"
or
java-home = "\\Program Files\\Java\\jdk1.8.0_211"

i would suggest adding the information above to README.md

for completeness, here is some suggested documentation text for the comments about java-home:

# Set JAVA_HOME
# Type: string
# change JDK directory name to reflect your environment.
# if on windows the path should be something like "/Program Files/Java/jdk1.8.0_211" 
java-home = "/usr/lib/jvm/default
